### ISSUE TITLE
Nuget Package Source Mapping Problem

### ISSUE THREAD

**Issue by chkoella** [MicrosoftDocs/azure-devops-yaml-schema#100]
This page should contain a note about the NuGet package source mapping problems or even suggest to use the CmdLine Task instead. 
see: 
https://github.com/microsoft/azure-pipelines-tasks/issues/15542#issuecomment-982018356
https://learn.microsoft.com/en-us/nuget/consume-packages/package-source-mapping
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/cmd-line-v2?view=azure-pipelines
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5825539f-634b-03d6-35f0-b532177a5e3b
* Version Independent ID: 5825539f-634b-03d6-35f0-b532177a5e3b
* Content: [DotNetCoreCLI@2 - .NET Core v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/dotnet-core-cli-v2?view=azure-pipelines)
* Content Source: [task-reference/dotnet-core-cli-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/dotnet-core-cli-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by chkoella** [comment]
Maybe the "Important" section that recommends to use NugetAuthenticate that is currently in the Remarks could be moved right on top because the Syntax section is really long.

**Comment by chkoella** [comment]
I just found out that I can use the DotNetCoreCLI custom command instead of the CmdLine Task. The custom command does not make the nuget.config transformation but has the advantage (over CmdLine Task) that warnings and Errors are transformed by the Tasks custom Logger to the format that azure devops can detect as warnings and errors.

```
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: custom
    custom: build
    arguments: '$(BuildArguments) /WarnAsError'
```

So as of my current understanding of the matter i propose the following:

- Move the blue "Important" notice on top for better visibility.
- Mention the Problem with Package Source Mapping explicitly
- Point out which command do a nuget.config transform

**Comment by WilliamAntonRohm** [comment]
@chkoella -- Christian, thank you for your followup.

When you're suggesting changes like these to the documentation, it may be faster for you to submit the edit yourself via a Pull Request (PR). You can do so by following these steps:

- Navigate to the page of interest
- Select the "Edit" button at the top right of the page
- Select the "Pencil" icon on the right
- Modify the text within the text box in markdown format
- Name your file change and copy the link to your Git Issue into the "extended description" box
- Select "Propose file change"
- Select "Create pull request" on the 'Comparing changes' page
- Select "Create pull request" on the 'Open a pull request' page
- Wait for an author to review and approve the change request - this can take a bit depending on the complexity

Doing this will allow authors to directly add your text to the documentation. This also displays your github image on the page of authors, and list you as a contributor to the documentation.

It is your choice, and if you'd prefer we will make these changes.

**Comment by chkoella** [comment]
@WilliamAntonRohm thank you for your replay. I'll try to make a PR this weekend.

**Comment by steved0x** [comment]
Fixed with https://github.com/MicrosoftDocs/azure-devops-yaml-schema/pull/102
