### ISSUE TITLE
Update Documenation reg repo based trigger pipeline resource filter conditions

### ISSUE THREAD

**Issue by kohithms** [MicrosoftDocs/azure-devops-yaml-schema#101]
Hi Team,

Currently, MS doc shares below info as a reference to use Pipeline resources. But its not sharing the way to 
<h1> how to trigger down stream pipeline which is having pipeline resources with trigger options. </h1>

pipelines:
- pipeline: string # Required as first property. ID of the pipeline resource.  ([-_A-Za-z0-9]*)
  project: string # Project for the source; defaults to current project.. 
  source: string # Name of the pipeline that produces the artifact.. 
  version: string # The pipeline run number to pick the artifact, defaults to latest pipeline successful across all stages; used only for manual or scheduled triggers.. 
  branch: string # Branch to pick the artifact. Optional; defaults to all branches, used only for manual or scheduled triggers.. 
  tags: [ string ] # List of tags required on the pipeline to pickup default artifacts. Optional; used only for manual or scheduled triggers. 
  trigger:  # Specify none to disable, true to include all branches, or use the full syntax as described in the following examples.
    enabled: boolean # Whether the trigger is enabled; defaults to true..  (false,n,no,off,on,true,y,yes)
    branches:  # Branch conditions to filter the events, optional; Defaults to all branches.
      include: [ branchFilter ] # List of branches to include. 
      exclude: [ branchFilter ] # List of branches to exclude. 
    stages: [ string ] # List of stages that when complete will trigger the pipeline. 
    tags: [ string ] # List of tags that when matched will trigger the pipeline.
-------------------

As an example MS doc shows below snippet,.

resources:
  pipelines:
  - pipeline: MyAppA
    source: MyCIPipelineA
  - pipeline: MyAppB
    source: MyCIPipelineB
    trigger: true
  - pipeline: MyAppC
    project:  DevOpsProject
    source: MyCIPipelineC
    branch: releases/M159
    version: 20190718.2
    trigger:
      branches:
        include:
        - main
        - releases/*
        exclude:
        - users/*

I would like to propose addition of tag based filter to the trigger section. PFB the scenario. 

Scenario: 

Main stream pipeline triggered based on a tag starts with V ( ex; V1.2.2 / V1.323.0.0 , V3.44.02 etc). If downstream pipeline needs to trigger only main stream pipeline triggers based on above tags then below confiuration is what expected in the documentation. 

resources:
  pipelines:
  - pipeline: MyAppA
    source: MyCIPipelineA
  - pipeline: MyAppB
    source: MyCIPipelineB
    trigger: true
  - pipeline: MyAppC
    project:  DevOpsProject
    source: MyCIPipelineC
    branch: releases/M159
    version: 20190718.2
    trigger:
      branches:
        include:
        - main
        - releases/*
        **- refs/tags/v*  #based on the tags on Repo this filter will help to trigger this pipeline.**
        exclude:
        - users/*

Kindly review and do needful.

Ref link discussed over here

https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/resources-pipelines-pipeline?view=azure-pipelines#examples

https://learn.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops

sample Pipeline yaml code: 
https://github.com/kohithms/Scripts/tree/master/TriggerDownstreamPipelineBasedOnUpstream

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bb60190b-fc26-9eb2-70c3-a8b1a0227658
* Version Independent ID: bb60190b-fc26-9eb2-70c3-a8b1a0227658
* Content: [resources.pipelines.pipeline definition](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/resources-pipelines-pipeline?view=azure-pipelines#examples)
* Content Source: [content/resources-pipelines-pipeline.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/resources-pipelines-pipeline.md)
* Service: **azure-devops-pipelines**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@kohithms -- Kohith, thank you for your very thorough feedback!

@steved0x -- Steve, please look into this issue.

**Comment by kohithms** [comment]
Hi @WilliamAntonRohm  / @steved0x  any update on this ?

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
