### ISSUE TITLE
Prompt Runtime variables Input in ManualValidation@0 step

### ISSUE THREAD

**Issue by mananshah-inspirato** [MicrosoftDocs/azure-devops-yaml-schema#106]
[Enter feedback here]
Hi! Currently the ManualValidation@0 works just fine with an input to enter 'Comment'. Can we add one more input prompt for passing variables, for my specific case I need it for adding 'version'  which would be of great value for Continuous Deployment to Prod and tagging version

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 12456d17-ff9d-eac6-7c70-22fad9bc2a26
* Version Independent ID: 12456d17-ff9d-eac6-7c70-22fad9bc2a26
* Content: [ManualValidation@0 - Manual validation v0 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/manual-validation-v0?view=azure-pipelines)
* Content Source: [task-reference/manual-validation-v0.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/manual-validation-v0.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by mananshah-inspirato** [comment]
@steved0x Any update here? Also is there a way for this task to assign dedicated approvers for this step as currently this step can be approved by anybody who has access to the pipelines. I am talking about a similar functionality where we could add specific  approvers just like 'Approval Gate' in AZDO

**Comment by steved0x** [comment]
@mananshah-inspirato This repository is for doc issues and your feedback is more like a feature request, to add new functionality to the task. You can file that request here:
https://github.com/microsoft/azure-pipelines-tasks/issues
or here: 
https://developercommunity.visualstudio.com/AzureDevOps

You can see the current list of issues for ManualValidation here, in case someone else has requested this before, you can add a comment in support of that change.
https://github.com/microsoft/azure-pipelines-tasks/issues?q=is%3Aissue+ManualValidation+

If I have misunderstood and your request is to update the docs to cover current functionality, please reactivate this issue.

Thank you,
Steve
