### ISSUE TITLE
CopyFiles@2 task does not expand variables in Contents field

### ISSUE THREAD

**Issue by chitturs** [MicrosoftDocs/azure-devops-yaml-schema#111]
This took a bit of debugging to figure, so raising this. The "does not work" snippet has no errors in the build pipeline but doesn't copy the file.

**// Does not work**
          - task: CopyFiles@2
            displayName: 'Copy subscription $(Aks.SubscriptionId) Configuration.json to $(ob_outputdirectory)'
            inputs:
              flattenFolders: true # need to copy the file to one artifacts folder. Makes it easy to deploy to EV2 since all files are in the same folder.
              Contents: $(Build.SourcesDirectory)/src/Linux/AKS/EV2-Deploy/CommonScopeBindings/subscriptions/$(Aks.SubscriptionId)/Configuration.json
              TargetFolder: '$(ob_outputdirectory)'

**// Works**
          - task: CopyFiles@2
            displayName: 'Copy subscription $(Aks.SubscriptionId) Configuration.json to $(ob_outputdirectory)'
            inputs:
              flattenFolders: true # need to copy the file to one artifacts folder. Makes it easy to deploy to EV2 since all files are in the same folder.
              SourceFolder: '$(Build.SourcesDirectory)/src/Linux/AKS/EV2-Deploy/CommonScopeBindings/subscriptions/$(Aks.SubscriptionId)'
              Contents: Configuration.json
              TargetFolder: '$(ob_outputdirectory)'

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1a08d700-66df-67d4-ac5e-3140af00f014
* Version Independent ID: 1a08d700-66df-67d4-ac5e-3140af00f014
* Content: [CopyFiles@2 - Copy files v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/copy-files-v2?view=azure-pipelines&tabs=yaml)
* Content Source: [task-reference/copy-files-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/copy-files-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
I believe you may have found a bug in the task itself, as the examples that were provided by the task owner show that variables can be used in the Contents field, and those variables should be available to all of the task inputs equally (any string parameters for task inputs are the same and the variable expansion would happen before the task runs.

Would you mind filing your report here?
[Issues · microsoft/azure-pipelines-tasks (github.com)](https://github.com/microsoft/azure-pipelines-tasks/issues)

I will track that and if there is a documentation fix that needs to be made after they evaluate it, I will make the update.

Thank you for letting us know.
