### ISSUE TITLE
PublishPipelineArtifact@1 has no option to preserve linux file premissions

### ISSUE THREAD

**Issue by AnderssonPeter** [MicrosoftDocs/azure-devops-yaml-schema#112]
I moved from `PublishBuildArtifacts@1` to `PublishPipelineArtifact@1` as that is suggested on some page I can't find any more.

The problem is that `PublishBuildArtifacts@1` has a option (`StoreAsTar`) to tar the output, this in turn preserves the executable permission of files.
`PublishPipelineArtifact@1` lacks this flag and results in the loss of the executable permission.

Is there any chance you could add a `StoreAsTar` to `PublishPipelineArtifact@1` simplify pipelines?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c01cefb9-8cb3-58aa-d1d1-33de985e49e6
* Version Independent ID: c01cefb9-8cb3-58aa-d1d1-33de985e49e6
* Content: [PublishPipelineArtifact@1 - Publish Pipeline Artifacts v1 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-pipeline-artifact-v1?view=azure-pipelines)
* Content Source: [task-reference/publish-pipeline-artifact-v1.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/publish-pipeline-artifact-v1.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
