### ISSUE TITLE
PublishCodeCoverageResults@2 documentation should describe what coverage formats are supported

### ISSUE THREAD

**Issue by idontusenumbers** [MicrosoftDocs/azure-devops-yaml-schema#114]
The documentation for this task does not yet include any information on what types of coverage data can be ingested. Based on context clues, it seems to support `cobertura` and `clover` formats. It would be helpful to explicitly describe which formats are supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: faca1d26-d98d-e263-da8b-0bc97896b69c
* Version Independent ID: faca1d26-d98d-e263-da8b-0bc97896b69c
* Content: [PublishCodeCoverageResults@2 - Publish code coverage results v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-code-coverage-results-v2?view=azure-pipelines)
* Content Source: [task-reference/publish-code-coverage-results-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/publish-code-coverage-results-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@idontusenumbers -- Charlie, thank you again for your feedback.

@steved0x -- Steve, please look into this issue.

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
