### ISSUE TITLE
The description needs explanation

### ISSUE THREAD

**Issue by EdCorteva** [MicrosoftDocs/azure-devops-yaml-schema#118]
The text says:
Variables are [Build](https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables) and [Release](https://learn.microsoft.com/en-us/azure/devops/pipelines/release/variables#default-variables). Wildcards are supported.

That is no help whatsoever.  Since I cannot find a decent description, here's what I would suggest in English:

=================================

A path descriptor for which folder(s) to include while performing the variable string replacement.  This value may contain wildcards as well as predefined variables described here: Build and Release. 

Example (all folders below the release folder containing the structure as built):
   blalblabla

Note that if too many folders are specified by this path that you will receive an error: [The errors that show up when screwing with this trying to figure it out]
==============================

It's easy to just take developer notes and assume that they make sense.  But developers are not writers, and they write from tribal knowledge.  It has to be described in a way to train and that can be referenced by persons without experience, like the epic SQL Server documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5cca65aa-222a-5789-3821-f5bb31f30013
* Version Independent ID: 5cca65aa-222a-5789-3821-f5bb31f30013
* Content: [FileTransform@1 - File transform v1 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/file-transform-v1?view=azure-pipelines)
* Content Source: [task-reference/file-transform-v1.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/file-transform-v1.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
