### ISSUE TITLE
Preview terminology

### ISSUE THREAD

**Issue by JFolberth** [MicrosoftDocs/azure-devops-yaml-schema#119]
I noticed that Azure Load testing is GA and that this page lists it as preview. Does the document need to be updated or is the task in preview?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: da03f378-cb72-ed75-d7af-6effd7a91487
* Version Independent ID: da03f378-cb72-ed75-d7af-6effd7a91487
* Content: [AzureLoadTest@1 - Azure Load Testing v1 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-load-test-v1?view=azure-pipelines)
* Content Source: [task-reference/azure-load-test-v1.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/azure-load-test-v1.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@JFolberth -- thank you for catching this.  I am updating the article.
