### ISSUE TITLE
AzureResourceManagerTemplateDeployment@3 does not actually accept subscription name

### ISSUE THREAD

**Issue by odegroot** [MicrosoftDocs/azure-devops-yaml-schema#121]
The "ARM template deployment v3" task takes an `subscriptionId` as input. This input has an alias: `subscriptionName`. It only accepts a subscription ID as value though: attempting to supply a subscription name results in the task failing to create a deployment.

```
Checking if the following resource group exists: my-rg.
##[error]Check out the troubleshooting guide to see if your issue is addressed: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops#troubleshooting
##[error]Failed to check the resource group status. Error: {"statusCode":400}.
```

Can you make this clear in the docs?
Either by removing the mention of the `subscriptionName` alias, or by adding a sentence that subscription names are not accepted, i.e. even if you use the `subscriptionName` alias, you still have to use the subscription ID as value.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 39f9c731-0172-2061-b972-3870d69ac358
* Version Independent ID: 39f9c731-0172-2061-b972-3870d69ac358
* Content: [AzureResourceManagerTemplateDeployment@3 - ARM template deployment v3 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-resource-manager-template-deployment-v3?view=azure-pipelines#remarks)
* Content Source: [task-reference/azure-resource-manager-template-deployment-v3.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/azure-resource-manager-template-deployment-v3.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@odegroot Thank you for reporting this issue. I have added an "important" note to that parameter to emphasize that it must be a subscription ID and not the name. I was going to file an issue, but looking at the source for that task reveals that the parameter was originally named "subscriptionName" and then the alias of "subscriptionId" was added later:

https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureResourceManagerTemplateDeploymentV3/task.json#L72

More details: https://github.com/Microsoft/azure-pipelines-tasks/blob/master/docs/authoring/yaml-tasks.md#making-life-easier-for-yaml-users

This makes it difficult to change, but the note I have added will make it clear.

<img width="346" alt="image" src="https://user-images.githubusercontent.com/1580889/223243611-6cee8c7c-a6d1-4c18-ba46-e81d753ff8ce.png">

Thank you for letting us know.
