### ISSUE TITLE
AzureRM not supported on self-hosted agent in Version 5

### ISSUE THREAD

**Issue by impact79** [MicrosoftDocs/azure-devops-yaml-schema#122]
Hello,
i had a quick glance at the code of the task in github and it seems that AzureRM is not supported for self-hosted agents in V5 any more. The remarks / troubleshooting page is misleading in this case.

Regards,
Holger
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5de2083f-ba71-fce1-ec99-91ee90d0d001
* Version Independent ID: 5de2083f-ba71-fce1-ec99-91ee90d0d001
* Content: [AzurePowerShell@5 - Azure PowerShell v5 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-powershell-v5?view=azure-pipelines&viewFallbackFrom=azure-devops)
* Content Source: [task-reference/azure-powershell-v5.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/azure-powershell-v5.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@impact79 -- Holger, thank you for your close reading.

@steved0x -- Steve, please look into this issue.

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
