### ISSUE TITLE
AzureResourceManagerTemplateDeployment: csmParametersFile documentation is for Link type

### ISSUE THREAD

**Issue by carlin-q-scott** [MicrosoftDocs/azure-devops-yaml-schema#123]
The documentation under the **csmParametersFile** heading is for **csmParametersFileLink**. It should just say it is a local file reference like the **csmFile** documentation.

The local files should have an example in them to make it easier to understand.

Finally, I think the inputs are poorly named for this task. The inputs that **don't** have `Link` appended to the end go with `templateLocation: Linked artifact`. That is confusing. I think the word Link in the input names should be replaced with Url.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 39f9c731-0172-2061-b972-3870d69ac358
* Version Independent ID: 39f9c731-0172-2061-b972-3870d69ac358
* Content: [AzureResourceManagerTemplateDeployment@3 - ARM template deployment v3 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-resource-manager-template-deployment-v3?view=azure-pipelines)
* Content Source: [task-reference/azure-resource-manager-template-deployment-v3.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/azure-resource-manager-template-deployment-v3.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
>The documentation under the **csmParametersFile** heading is for **csmParametersFileLink**. It should just say it is a local file reference like the **csmFile** documentation.

@carlin-q-scott I'll fix that task input description, thank you for catching that. It looks like there was a copy/paste error with the other task input that you named. I will revert the description back to the one provided in the task source code, which is here: https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureResourceManagerTemplateDeploymentV3/task.json#L164

> Finally, I think the inputs are poorly named for this task. The inputs that **don't** have `Link` appended to the end go with `templateLocation: Linked artifact`. That is confusing. I think the word Link in the input names should be replaced with Url.

To provide feedback on the task input names (there is a similar PR going on right now with a similar naming issue on the Maven task) you can file an issue or a PR into the open source task repo using the link provided above. We could add a few notes into the task article to help clarify, if that would help? Although much of the tasks articles are auto-generated (including the parameter names and the initial content for their descriptions), there is the capability to add additional notes and comments. See [Contributing to tasks content](https://github.com/MicrosoftDocs/azure-devops-yaml-schema#contributing-to-the-tasks-content).

> The local files should have an example in them to make it easier to understand.

I will try to get an example together to add.
