### ISSUE TITLE
cacheHitVar is set to "inexact" when using a restore key

### ISSUE THREAD

**Issue by eartle** [MicrosoftDocs/azure-devops-yaml-schema#129]
When restoring the cache from a restore key, cacheHitVar is set to "inexact". The docs say it's only ever "true" or "false".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b04ad6d6-d7ee-fc6e-759a-855fa99f1296
* Version Independent ID: b04ad6d6-d7ee-fc6e-759a-855fa99f1296
* Content: [Cache@2 - Cache v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/cache-v2?view=azure-pipelines)
* Content Source: [task-reference/cache-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/cache-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
