### ISSUE TITLE
Conditions link on page points to 404

### ISSUE THREAD

**Issue by qJake** [MicrosoftDocs/azure-devops-yaml-schema#130]
Under `successCriteria`, this paragraph:

> Example: For response {"status" : "successful"}, the expression can be eq(root['status'], 'successful'). Learn more about [specifying conditions](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/conditions&tabs=yaml).

The link "*specifying conditions*" results in a 404. The link should be updated to point to the correct page. (I'm not sure what the correct URL is.)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 038b734f-c824-15a1-f256-de92abce5dc3
* Version Independent ID: 038b734f-c824-15a1-f256-de92abce5dc3
* Content: [InvokeRESTAPI@1 - Invoke REST API v1 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/invoke-rest-api-v1?view=azure-pipelines&tabs=yaml)
* Content Source: [task-reference/invoke-rest-api-v1.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/invoke-rest-api-v1.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@qJake -- Jake, I have updated the documentation and it should be live by tomorrow.
