### ISSUE TITLE
Deploy test without run

### ISSUE THREAD

**Issue by Ben-Duf** [MicrosoftDocs/azure-devops-yaml-schema#141]
Hello,

this task is really great and I actually deploy my versionned tests with it.

now I need to deploy the new configuration of the test, but not running it.
is there any option in the task to do so ?

for exemple, when creating a test in the Azure Portal, the is a checkbox named "Run test after creation" that I would uncheck.

thanks for your help
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: da03f378-cb72-ed75-d7af-6effd7a91487
* Version Independent ID: da03f378-cb72-ed75-d7af-6effd7a91487
* Content: [AzureLoadTest@1 - Azure Load Testing v1 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-load-test-v1?view=azure-pipelines&viewFallbackFrom=azure-devops)
* Content Source: [task-reference/azure-load-test-v1.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/azure-load-test-v1.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@Ben-Duf -- thank you for your positive feedback!  Please add your suggestion here:
- [Azure DevOps Feedback](https://developercommunity.visualstudio.com/AzureDevOps)

cc @steved0x for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
