### ISSUE TITLE
Looking for "env: string:" example

### ISSUE THREAD

**Issue by austinledbetter** [MicrosoftDocs/azure-devops-yaml-schema#151]
It looks like there is an "env: string:" parameter, and it would be nice to see an example here of how to use it.  I found an example of it here - https://stackoverflow.com/questions/64020523/how-to-add-env-vars-into-azure-devops-pipeline

and I tried to implement it like this:

`
          - script: |
              git checkout master
              
              git checkout $SOURCEBRANCH
              git diff --unified=0 master $SOURCEBRANCH | ProcessDiff.exe pipe
            displayName: Running branch check
            workingDirectory: $(Build.SourcesDirectory)/HHH.Monolith
            condition: and(succeeded(), contains(variables['build.sourceBranch'], 'refs/heads'))
            env:
              SOURCEBRANCH: $[replace(variables['build.sourcebranchname'], 'refs/heads/', '')]
`
and 

`
            env:
              SOURCEBRANCH: {{ $[replace(variables['build.sourcebranchname'], 'refs/heads/', '')] }}
`

but it both cases the pipeline throws an error "Expected mapping end".  

I don't know if the example I hunted down is wrong or the way I am trying to do my replace is wrong, but it would be nice to have some official documentation around the env parameter so I could rule out part of the issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d7fab726-1c6c-b629-9a8a-a39180634b81
* Version Independent ID: d7fab726-1c6c-b629-9a8a-a39180634b81
* Content: [steps.script definition](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-script?view=azure-pipelines)
* Content Source: [content/steps-script.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/steps-script.md)
* Service: **azure-devops-pipelines**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@austinledbetter -- thank you for your feedback.  Please consider this resource:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/)

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
