### ISSUE TITLE
publishTestResults does not publish code coverage how one might expect

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/azure-devops-yaml-schema#152]
The description for `publishTestsResults` is "Publish test results and code coverage."

Later on, it says "Code coverage can be collected by adding the --collect “Code coverage” option to the command line arguments."

If you use this in a pipeline with `System.Debug` enabled:

```yaml
  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: 'test'
      projects: '**/*.csproj'
      arguments: '--collect:"XPlat Code Coverage"'
      publishTestResults: true
```

You can see this in the logs:

> ##[debug]File uploaded successsfully on LogStore coverage.cobertura.xml
> ##[debug]File uploaded successsfully on LogStore VssAdministrator_fv-az341-996_2023-04-06_18_28_11.trx
> Published Test Run : https://XXXX.visualstudio.com/XXXX/_TestManagement/Runs?runId=1234&_a=runCharts

But if you go to the pipeline UI, you won't see it there.

![image](https://user-images.githubusercontent.com/1784452/230466344-984a931f-6243-42c2-99e5-8e999e34d564.png)

That's because it's actually getting uploaded to the 3rd line shown from the logs.

From there, you can download the coverage files.

It was confusing to me that it says that it publishes code coverage, but not to where I was expecting. After all, test results are getting uploaded to two places and code coverage is getting uploaded to one place.

Could we update the documentation to clarify where the files are published to?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5825539f-634b-03d6-35f0-b532177a5e3b
* Version Independent ID: 5825539f-634b-03d6-35f0-b532177a5e3b
* Content: [DotNetCoreCLI@2 - .NET Core v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/dotnet-core-cli-v2?view=azure-pipelines)
* Content Source: [task-reference/dotnet-core-cli-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/dotnet-core-cli-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
