### ISSUE TITLE
Maximum supported length of inline script is not documented for AzurePowerShell@5 task

### ISSUE THREAD

**Issue by BastiaanMolsbeck** [MicrosoftDocs/azure-devops-yaml-schema#157]
The maximum supported length of inline script is not documented for the AzurePowerShell@5 task:
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-powershell-v5?view=azure-pipelines

If you for instance look at the documentation for the PowerShell@2 task, the maximum supported script length is documented:
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/powershell-v2?view=azure-pipelines

Can this be added to the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5de2083f-ba71-fce1-ec99-91ee90d0d001
* Version Independent ID: 5de2083f-ba71-fce1-ec99-91ee90d0d001
* Content: [AzurePowerShell@5 - Azure PowerShell v5 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-powershell-v5?view=azure-pipelines)
* Content Source: [task-reference/azure-powershell-v5.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/azure-powershell-v5.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@BastiaanMolsbeck I will find out the limit and add it to the article. Thanks for letting us know.
