### ISSUE TITLE
Where can I see the Changes between Task Versions (e.g. from @3 to @4)

### ISSUE THREAD

**Issue by in-fke** [MicrosoftDocs/azure-devops-yaml-schema#160]
Where can I see the release notes _between Task Versions_ (e.g. from `@3` to `@4`).
Can they be linked from the Documentation to the corresponding GitHub Page?
Or could the `See also` section link to the corresponding GitHub README?

THANK YOU

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b5761f1d-d153-3e5f-dd28-7ec14af997a3
* Version Independent ID: b5761f1d-d153-3e5f-dd28-7ec14af997a3
* Content: [Maven@4 - Maven v4 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/maven-v4?view=azure-pipelines)
* Content Source: [task-reference/maven-v4.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/maven-v4.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@in-fke -- thank you for your questions.  You have probably noticed this in the TOC for this article:
![image](https://user-images.githubusercontent.com/27738025/235002369-ea13036a-2a47-4fb8-99a7-ba52ff27a3d0.png)

As to a list of changes between versions, I'm not sure.

@steved0x -- are there such release notes?

**Comment by in-fke** [comment]
Yes the versioned TOC is good, but Release Notes would give a more precise information.
Comparing the versions manually is not practical.

**Comment by steved0x** [comment]
@in-fke Some tasks have release notes, but many do not, and they are often very brief. When they are present we try to include them. And we don't have an automated version of differences, like "xyz property added, 3 new allowed values added, etc". That is a good idea, and I am going to see if we can get a list of "What's new/different" with a new task version, and put it in the remarks section of a task. You have found the GH page for the tasks, so you can look at the PRs and commits to see what is changed, but that is tough as there are often a lot of localization and task runner types of PRs that touch many files.

Thank you for the great suggestion.
