### ISSUE TITLE
Invalid `versioningScheme` detail

### ISSUE THREAD

**Issue by chrish619** [MicrosoftDocs/azure-devops-yaml-schema#167]
`versioningScheme` is listed as having 4 options: `off`, `byPrereleaseNumber`, `byEnvVar`, and `byBuildNumber`.

The options are then listed as: `byPrereleaseNumber`, `byEnvVar` and `true`.

`true` is an invalid option, and should be `byBuildNumber`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6054b71e-9f19-999e-8fc2-87fca2e99ffe
* Version Independent ID: 6054b71e-9f19-999e-8fc2-87fca2e99ffe
* Content: [NuGetCommand@2 - NuGet v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/nuget-command-v2?view=azure-pipelines)
* Content Source: [task-reference/nuget-command-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/nuget-command-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@chrish619 Thank you for letting us know. I'll get that fixed and it should be live by later today.
