### ISSUE TITLE
Add section about trigger.paths and how to include and exclude specific paths

### ISSUE THREAD

**Issue by nevva** [MicrosoftDocs/azure-devops-yaml-schema#170]
Add section about pipelines.trigger.paths and how you can include and exclude specific paths. Some of the information on this page would fit pretty well:
https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#paths

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: db702258-9035-fa1e-33be-414a79c9655e
* Version Independent ID: db702258-9035-fa1e-33be-414a79c9655e
* Content: [resources.pipelines.pipeline.trigger definition](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/resources-pipelines-pipeline-trigger?view=azure-pipelines)
* Content Source: [content/resources-pipelines-pipeline-trigger.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/resources-pipelines-pipeline-trigger.md)
* Service: **azure-devops-pipelines**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
