### ISSUE TITLE
fetchDepth documentation

### ISSUE THREAD

**Issue by JasonKleban** [MicrosoftDocs/azure-devops-yaml-schema#173]
> fetchDepth string.
> Depth of Git graph to fetch.

This is usually "1" in practice, but this document wouldn't help me get there.  Also, what are the range of reasonable string values?  "7"?  "1000"?  a date string?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b28abf7f-ecdf-8037-acd9-722690424372
* Version Independent ID: b28abf7f-ecdf-8037-acd9-722690424372
* Content: [steps.checkout definition](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelines)
* Content Source: [content/steps-checkout.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/steps-checkout.md)
* Service: **azure-devops-pipelines**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
