### ISSUE TITLE
There are two 'that' words.

### ISSUE THREAD

**Issue by SanaICP** [MicrosoftDocs/azure-devops-yaml-schema#176]
Hello Microsoft,

You have included the two 'that' words in the bigging of this document.

![Screenshot 2023-06-07 183132](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/assets/135840571/b13a64db-11da-40a1-b1ca-320a332d3459)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0029948d-6054-90c7-1dd1-450177589741
* Version Independent ID: 0029948d-6054-90c7-1dd1-450177589741
* Content: [variables definition](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/variables?view=azure-pipelines)
* Content Source: [content/variables.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/variables.md)
* Service: **azure-devops-pipelines**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Hello @SanaICP!  Thank you for bringing this to our attention.  I am updating this documentation.

**Comment by SanaICP** [comment]
Hello William,

You are welcome.

Best Regards.
________________________________
