### ISSUE TITLE
Clarify what directory paths are relative to

### ISSUE THREAD

**Issue by GreenBattery** [MicrosoftDocs/azure-devops-yaml-schema#190]
[Enter feedback here]

On this documentation page, it would be helpful to specify the relevant context information, such as when specifying a `paths` `include` or `exclude` inputs for a pipeline trigger, that relative paths are relative to the root of the source code repository. 

This makes the documentation more informative and reduces the need to figure things out by trial and error. 

Additionally, it would be helpful to clarify the *logical* way that triggers are interpreted. 

For example, from trial and error, it seems to me that 
```yaml
trigger:
   branches:
      include:
         - 'main'
   paths:
      include:
         - foo
         - bar
```

should be interpreted as: `trigger when the branch includes main *AND* (the path is 'foo' *OR* 'bar' )`
This is not clear from the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 428d5e92-b3bd-c992-89bf-021bb27233e3
* Version Independent ID: 428d5e92-b3bd-c992-89bf-021bb27233e3
* Content: [trigger definition](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/trigger?view=azure-pipelines#triggerobjectproperties)
* Content Source: [content/trigger.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/trigger.md)
* Service: **azure-devops-pipelines**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
