### ISSUE TITLE
Link to YAML reference for steps.task in the Index for the Pipelines Task Reference

### ISSUE THREAD

**Issue by GreenBattery** [MicrosoftDocs/azure-devops-yaml-schema#191]
[Enter feedback here]

On the Tasks Reference page, there should be a link to the YAML reference for steps.task. This is needed because it is not obvious to a reader from reading the documentation for a specific task what other keys are valid in the context of a steps.task. 

For example, reading the documentation for Powershell@2 task, you would not realise that it is possible to supply an `env` object that represents values you want to set in the environment for that ask. I was only able to discover this after a significant
amount of time researching, encountering several "undocumented" attributes of steps.task that I stumbled upon the YAML reference section of the documentation, which is well-hidden and rarely linked to from task documentation. 

In Lieu perhaps of linking to the reference: [YAML Reference for steps.task](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-task?view=azure-pipelines) from every task's documentation in the See Also section,
it may perhaps be sufficient to highlight that each documented task supports other attributes, all of which are documented at: [YAML Reference for steps.task](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-task?view=azure-pipelines)

I've also only just now realised that I could make a PR and update the documentation myself, which I don't mind doing, however, it appears that the index.md for tasks reference doesn't have any `editable-content` sections, so my PR would probably be automatically rejected. Let me know if a PR would indeed be welcome for this and I shall have a go at it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43fa0ed2-c019-541a-495e-61c7510a7048
* Version Independent ID: 43fa0ed2-c019-541a-495e-61c7510a7048
* Content: [Azure Pipelines task reference](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/?view=azure-pipelines)
* Content Source: [task-reference/index.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/index.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@GreenBattery -- thank you for your thorough feedback, and your kind offer.  If you create a PR for this information, I will shepherd it into the documentation files.

**Comment by steved0x** [comment]
@GreenBattery This is great feedback and I see that you have submitted a PR - that PR will be live shortly, thank you.
