### ISSUE TITLE
VSTest@2: Confusion about 2 different doc files

### ISSUE THREAD

**Issue by schibu007** [MicrosoftDocs/azure-devops-yaml-schema#196]
It seems that there is another file with similar content:
https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/includes/yaml/VsTestV2.md
This file includes the changes proposed by the issue:
https://github.com/MicrosoftDocs/azure-devops-docs/issues/1580
But the current [doc](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/vstest-v2?view=azure-pipelines) does not. I'm writing because I have trouble similar to the ones described in the issue above.

Which of the files is "valid"? Do we need both of them?

May you please have a look into this? Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5a378422-4758-62c7-1793-7ce4724079aa
* Version Independent ID: 5a378422-4758-62c7-1793-7ce4724079aa
* Content: [VSTest@2 - Visual Studio Test v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/vstest-v2?view=azure-pipelines)
* Content Source: [task-reference/vstest-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/vstest-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
That older version is archived, I am making the update to our new version and it should be live today.
