### ISSUE TITLE
Put `current` as the usual value to put in

### ISSUE THREAD

**Issue by trajano** [MicrosoftDocs/azure-devops-yaml-schema#2]
Rather than making us go to https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops

Say it here

download

string
Required. must be `current`

Using a different value like `specific` does not make sense unless the other parameters like `pipeline` and `project` are documented and allowed.  If allowed then the text should be

Download artifacts produced by the current pipeline run, or from a specific pipeline run.  Use `current` to download artifacts from the current pipeline or use `specific` to reference another pipeline via `project` and `pipeline` arguments.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0727646b-b2de-43e7-66bb-4d1a4e149801
* Version Independent ID: 0727646b-b2de-43e7-66bb-4d1a4e149801
* Content: [steps.download definition](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-download?view=azure-pipelines)
* Content Source: [content/steps-download.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/steps-download.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@trajano Thank you for the feedback. It looks like the download step is a shortcut for downloading an artifact from the current pipeline. I'll clarify this and get it published shortly. Thank you.
