### ISSUE TITLE
Parameters could have descriptions to be used as hints for whoever runs the pipeline

### ISSUE THREAD

**Issue by Jmorjsm** [MicrosoftDocs/azure-devops-yaml-schema#200]
It would be helpful if parameters could take a description which could then be displayed as a tooltip/help-text when a pipeline run is being triggered. 
This could help users to run pipelines and tweak the behaviour without prior knowledge of the actual pipeline definition, just the information provided on the trigger modal.

**Comment by WilliamAntonRohm** [comment]
@Jmorjsm -- Jon, thank you for your suggestions.  Please add them here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
