### ISSUE TITLE
clarify override parameter usage with objects.

### ISSUE THREAD

**Issue by housten** [MicrosoftDocs/azure-devops-yaml-schema#201]
This one line is all there is on sending an object in for parameters.
> To override object type parameters, use stringified JSON objects. For example, -options ["option1"] -map {"key1": "value1" }

It would be great to know how one should be stringifying objects to get the syntax above. I went with the pipeline convertToJson function `${{ convertToJson(overrideparams) }}` but that results in this (no quotes) :
```
{
   apim_instance: demo-apim-dev
}
```
It appears that the syntax in the documentation may not work as written either - at least [this stackoverflow question](https://stackoverflow.com/questions/66258727/how-to-pass-object-to-overrideparameters-for-arm-deployment-from-yaml-pipeline) is unanswered (there is an answer but it doesn't recognize that the original poster appears to be sending in what the documentation says but gets an error about it being a string instead of an object...

Additonally, if there is a way to use an object containing all of the override parameters as an overrideparameter, could it be documented, or document that it isn't possible? For clarification, using the object json above, the parameter to override would be apim_instance, and that object json would contain all the other parameters the receiving bicep is expecting, including object type parameters...

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 440723cb-b52a-84d1-8b22-19d87be27488
* Version Independent ID: 440723cb-b52a-84d1-8b22-19d87be27488
* Content: [AzureResourceGroupDeployment@2 - Azure resource group deployment v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-resource-group-deployment-v2?view=azure-pipelines&viewFallbackFrom=azure-devops)
* Content Source: [task-reference/azure-resource-group-deployment-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/azure-resource-group-deployment-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@housten -- thank you for your clear feedback.  Please consider this resource:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 

@steved0x -- please look into this issue.

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
