### ISSUE TITLE
Please specify the workaround using max_old_space_size for Heap memory exhaustion error in AzureFunctionApp task documentations

### ISSUE THREAD

**Issue by hmitsu** [MicrosoftDocs/azure-devops-yaml-schema#204]
(Request)
Please specify the following workaround (using --max_old_space_size) for following heap errors in the AzureFunctionApp@1 and AzureFunctionApp@1 documentations  as a formal workaround for these heap errors.

workaround sample:
----
  - task: AzureFunctionApp@1
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      appType: "functionApp"
      appName: ${{ parameters.function }}
      package: "$(Build.ArtifactStagingDirectory)/${{ parameters.artifactName }}.zip"
      deploymentMethod: "auto"
    env:
      NODE_OPTIONS: --max_old_space_size=16384
------

Target Documentation:
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-function-app-v2?view=azure-pipelines
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-function-app-v1?view=azure-pipelines

(The Objective of this request)
Heap memory exhaustion for Java is occurring at the time when the pipeline AzureFunctionApp task is executed on the Azure Pipelines agent, which is causing the error as follows:
----
2023-07-03T07:07:50.3725723Z FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
...
2023-07-03T07:07:50.3771991Z  3: 0xb0336e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/agent/externals/node10/bin/node]
2023-07-03T07:07:50.3779690Z  4: 0xb035a4 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/agent/externals/node10/bin/node]
----

We  temporarily escaped these errors by using the above workaround sample.
However, this workaround is not officially guaranteed as a specification. 
Therefore, there is a risk that this workaround will be invalidated if the implementation of the AzureFunctionApp task is changed.
Please specify this workaround as a specification and officially state that it is effective as long as there is no explicit documentation change.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 87b190ff-4ca4-a7ca-381d-e97185d05df1
* Version Independent ID: 87b190ff-4ca4-a7ca-381d-e97185d05df1
* Content: [AzureFunctionApp@2 - Azure Functions Deploy v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-function-app-v2?view=azure-pipelines)
* Content Source: [task-reference/azure-function-app-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/azure-function-app-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
![Untitled](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/assets/101402334/cff89c80-a1fd-4fab-b3b2-445c813bcb43)

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
