### ISSUE TITLE
Bug in passing "TestCaseFilter" parameters to "vstest.console.exe" in "VSTest@2" task

### ISSUE THREAD

**Issue by v-galatrash** [MicrosoftDocs/azure-devops-yaml-schema#208]
Consider this code sample (fabricated for this post) which is part of tests running in Azure DevOps build/release pipeline:

```
// .NET Framework 4.8 project with referenc to these 2 packages:
//  <package id="MSTest.TestAdapter" version="3.1.1" targetFramework="net48" />
//  <package id="MSTest.TestFramework" version="3.1.1" targetFramework="net48" />

using Microsoft.VisualStudio.TestTools.UnitTesting;
namespace SampleTest
{
    [TestClass]
    public class Tests
    {
        [TestMethod]
        [DataRow(0)]
        [DataRow(1)]
        [DataRow(-1)]
        public void TestIsPositive(int x)
        {
            Assert.IsTrue(x >= 0);
        }
    }
}
```

When the VSTest@2 task in the pipeline has `rerunFailedTests: true`, the rerun fails with this message:
`Incorrect format for TestCaseFilter Missing Operator '|' or '&'. Specify the correct format and try again. Note that the incorrect format can lead to no test getting executed.`

From the logs, the executed command which produces this error is like this:
`vstest.console.exe "SampleTest.dll" /TestCaseFilter:"FullyQualifiedName=SampleTest.Tests.TestIsPositive (-1)"`

When I execute this command locally with a slight variation (adding a pipeline to the `/TestCaseFilter` parameter's start or end) like this:
`vstest.console.exe "SampleTest.dll" /TestCaseFilter:"FullyQualifiedName=SampleTest.Tests.TestIsPositive (-1)|"`
then the `vstest` executable will run all the 3 tests in the `TestIsPositive` method and not just the failing one.

Referring to this page [TestCase filter](https://github.com/Microsoft/vstest-docs/blob/main/docs/filter.md) I understand that the test cases must be escaped (when there are some characters as in the case of using `DataRow(...)]` or `[DynamicData(...)]`) **and especially if the tests have URL data that has query parameters in them.**

Here are a few variations to try (some will pass some will fail with different reasons):
```
vstest.console.exe "SampleTest.dll" /TestCaseFilter:"FullyQualifiedName=SampleTest.Tests.TestIsPositive"
vstest.console.exe "SampleTest.dll" /TestCaseFilter:"FullyQualifiedName=SampleTest.Tests.TestIsPositive (-1)"
vstest.console.exe "SampleTest.dll" /TestCaseFilter:"FullyQualifiedName=SampleTest.Tests.TestIsPositive (-1)|"
vstest.console.exe "SampleTest.dll" /TestCaseFilter:"|FullyQualifiedName=SampleTest.Tests.TestIsPositive (-1)"
vstest.console.exe "SampleTest.dll" /TestCaseFilter:"FullyQualifiedName=SampleTest.Tests.TestIsPositive (-1)|FullyQualifiedName=SampleTest.Tests.TestIsPositive (1)"
vstest.console.exe "SampleTest.dll" /TestCaseFilter:"FullyQualifiedName=SampleTest.Tests.TestIsPositive (-1)|FullyQualifiedName=SampleTest.Tests.TestIsPositive (1)|"
vstest.console.exe "SampleTest.dll" /TestCaseFilter:"FullyQualifiedName=SampleTest.Tests.TestIsPositive \(-1\)"
vstest.console.exe "SampleTest.dll" /TestCaseFilter:"FullyQualifiedName=SampleTest.Tests.TestIsPositive \(-1\)|"
vstest.console.exe "SampleTest.dll" /TestCaseFilter:"|FullyQualifiedName=SampleTest.Tests.TestIsPositive \(-1\)"
vstest.console.exe "SampleTest.dll" /TestCaseFilter:"FullyQualifiedName=SampleTest.Tests.TestIsPositive \(-1\)|FullyQualifiedName=SampleTest.Tests.TestIsPositive \(1\)"
```

Hence, this is to report a bug in which the `VSTest@2` task needs to properly escape the string passed in the rerun because as a developer using this task, I have no direct control over the parameters being generated by it and can't enforce escaping myself.

Regards,
George

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5a378422-4758-62c7-1793-7ce4724079aa
* Version Independent ID: 5a378422-4758-62c7-1793-7ce4724079aa
* Content: [VSTest@2 - Visual Studio Test v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/vstest-v2?view=azure-pipelines)
* Content Source: [task-reference/vstest-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/vstest-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@v-galatrash -- George, thank you for your detailed feedback.  Please this product issue here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)

cc @steved0x for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by v-galatrash** [comment]
Thanks @WilliamAntonRohm . I will post in the [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps) shortly.
