### ISSUE TITLE
jobs.deployment.environment.resourceName cannot be used

### ISSUE THREAD

**Issue by emmanuelbenitez** [MicrosoftDocs/azure-devops-yaml-schema#21]
When the resource name for a deployment job is set (as documented [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/jobs-deployment-environment?view=azure-pipelines#environment-name-resourcename-resourceid-resourcetype-tags)), you get this error: 
`Job XXXX: Resource YYYY does not exist in environment ZZZZ.`

I verified that the YYYY is member of the environment ZZZZ.

When the resource id is used, it works.

**Comment by ramiMSFT** [comment]
@emmanuelbenitez Can you try this syntax instead?
```yaml
environment: environmentName.resourceName
```

**Comment by ramiMSFT** [comment]
Closing this issue now, feel free to leave a comment if you're still facing this issue
