### ISSUE TITLE
`specificBuildWithTriggering` doesn't work with retries

### ISSUE THREAD

**Issue by TomONeill** [MicrosoftDocs/azure-devops-yaml-schema#219]
I've got 2 pipelines:
- Pipeline A
- Pipeline B

Pipeline B gets triggered by Pipeline A. Pipeline B downloads the artifacts from Pipeline A with option `specificBuildWithTriggering`.

This works fine except for the case where Pipeline B was cancelled and then retried.
Then Pipeline B will download the `latest` from Pipeline A, instead of the artifact that is listed under "Consumed", which is not something I expected.

I understand that a retry can be seen more as like a manual trigger, however, the `Build.Reason` is still the same (`ResourceTrigger` in my case).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6d5753b5-d4e7-6696-0230-3595f632ba0e
* Version Independent ID: 6d5753b5-d4e7-6696-0230-3595f632ba0e
* Content: [DownloadPipelineArtifact@2 - Download Pipeline Artifacts v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/download-pipeline-artifact-v2?view=azure-pipelines)
* Content Source: [task-reference/download-pipeline-artifact-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/download-pipeline-artifact-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@TomONeill -- Tom, thank you for your feedback.  If you feel this is a product issue, please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)

@steved0x -- Steve, please look into this potential documentation issue.

**Comment by TomONeill** [comment]
Added here: https://developercommunity.visualstudio.com/t/specificBuildWithTriggering-doesnt-work/10456459
