### ISSUE TITLE
'Path' description incorrect

### ISSUE THREAD

**Issue by GaTechThomas** [MicrosoftDocs/azure-devops-yaml-schema#22]
The 'path' field is defined incorrectly on this page as:

` Path of the repository to check out`

[Other documentation](https://github.com/Microsoft/azure-pipelines-yaml/blob/master/design/checkout-path.md)  describes it more accurately as:

`where to put the repo; always rooted at $(Pipeline.Workspace)`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b28abf7f-ecdf-8037-acd9-722690424372
* Version Independent ID: b28abf7f-ecdf-8037-acd9-722690424372
* Content: [steps.checkout definition](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelines)
* Content Source: [content/steps-checkout.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/steps-checkout.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@GaTechThomas That's great feedback, it should be live soon. Thank you.
