### ISSUE TITLE
Contradicting information about PublishCodeCoverageResults@1

### ISSUE THREAD

**Issue by Pentadome** [MicrosoftDocs/azure-devops-yaml-schema#225]
The article says: 
>Multiple summary files are merged into a single report.

But it also says
> If you provide multiple files as input to the task, only the first match is considered. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4887de94-7ea0-1c84-102e-1e4c1de503e2
* Version Independent ID: 4887de94-7ea0-1c84-102e-1e4c1de503e2
* Content: [PublishCodeCoverageResults@1 - Publish code coverage results v1 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-code-coverage-results-v1?view=azure-pipelines)
* Content Source: [task-reference/publish-code-coverage-results-v1.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/publish-code-coverage-results-v1.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
