### ISSUE TITLE
WindowsMachineFileCopy@2 CleanTargetBeforeCopy doesn't indicate it deletes directories as well as files.

### ISSUE THREAD

**Issue by AlexTurff** [MicrosoftDocs/azure-devops-yaml-schema#233]
Please clarify that the CleanTargetBeforeCopy setting will trigger the copy to delete all directories as well as all files. It may be worth indicating this is a "dangerous" option as it could have dangerous effects if run in the wrong directory

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d75c278-bc85-1e07-028e-e2f400ad5e0d
* Version Independent ID: 1d75c278-bc85-1e07-028e-e2f400ad5e0d
* Content: [WindowsMachineFileCopy@2 - Windows machine file copy v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/windows-machine-file-copy-v2?view=azure-pipelines)
* Content Source: [task-reference/windows-machine-file-copy-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/windows-machine-file-copy-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
