### ISSUE TITLE
Links in "Code coverage results for JavaScript with Istanbul using YAML" section are dead

### ISSUE THREAD

**Issue by wojtekmaj** [MicrosoftDocs/azure-devops-yaml-schema#236]
Links in "Code coverage results for JavaScript with Istanbul using YAML" section are dead. The page they ultimately lead to do not contain anything about "coverage", "istanbul", ot "cobertura".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: faca1d26-d98d-e263-da8b-0bc97896b69c
* Version Independent ID: faca1d26-d98d-e263-da8b-0bc97896b69c
* Content: [PublishCodeCoverageResults@2 - Publish code coverage results v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-code-coverage-results-v2?view=azure-pipelines)
* Content Source: [task-reference/publish-code-coverage-results-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/publish-code-coverage-results-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thank you for letting us know. It looks like that article was refactored into two articles, and those sections moved to "Customize JavaScript". I have update the two links in this task article and the previous version.

https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/customize-javascript?view=azure-devops#publish-code-coverage-results
