### ISSUE TITLE
YAML Schema page breaks Navigation Menu

### ISSUE THREAD

**Issue by craigb** [MicrosoftDocs/azure-devops-yaml-schema#24]
When looking at the References menu of the top-level devops/pipelines documentation, there are many items to select:
https://docs.microsoft.com/en-us/azure/devops/pipelines/?view=azure-devops
![image](https://user-images.githubusercontent.com/59184/178544902-dcccae0c-b7c1-47f2-b082-187e52f90295.png)

Clicking on Expressions, I see what I expect -- the navigation menu is updated with my position and I see the content for Expressions:
![image](https://user-images.githubusercontent.com/59184/178545071-8c321e17-18a1-4dcf-9f9b-9ff669deb252.png)

The bug appears when I click on the YAML schema. I lose my context on the left with no option to look at the other resources except via back button or editing the URL.
![image](https://user-images.githubusercontent.com/59184/178545284-4e019b61-e476-49e8-a343-a1d210e65329.png)

It feels like this should be expanded underneath a parent node so I have a quick escape hatch. Am I off-base here?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9316a0c0-9ccb-7bca-390f-771c9baa4e8d
* Version Independent ID: 9316a0c0-9ccb-7bca-390f-771c9baa4e8d
* Content: [YAML schema reference](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/?view=azure-pipelines&viewFallbackFrom=azure-devops)
* Content Source: [content/index.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@craigb -- Craig, thank you for your thorough feedback.  I am investigating.

**Comment by WilliamAntonRohm** [comment]
@craigb -- Craig, for now, please use the breadcrumb at the top of the page to return up a level:
`Docs > Azure DevOps > Azure Pipelines`

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
