### ISSUE TITLE
Mention Publish Pipeline Artifacts task replacement

### ISSUE THREAD

**Issue by cremor** [MicrosoftDocs/azure-devops-yaml-schema#240]
This page should mention that `PublishPipelineArtifact` is a replacement for it. Something similar to the following:

From [Artifacts in Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/artifacts/build-artifacts?view=azure-devops&tabs=yaml):
> We recommend using [Download Pipeline Artifacts](https://learn.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops#download-artifacts) and [Publish Pipeline Artifacts](https://learn.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops#publish-artifacts) for faster performance.

From [DownloadBuildArtifacts@1](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/download-build-artifacts-v1?view=azure-pipelines):
> The Azure Pipelines team recommends upgrading from build artifacts to [Pipeline Artifacts](https://learn.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts) for faster performance.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 63f373f1-1cce-fcbf-6ab3-1ef0705d5a80
* Version Independent ID: 63f373f1-1cce-fcbf-6ab3-1ef0705d5a80
* Content: [PublishBuildArtifacts@1 - Publish build artifacts v1 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-build-artifacts-v1?view=azure-pipelines)
* Content Source: [task-reference/publish-build-artifacts-v1.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/publish-build-artifacts-v1.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@cremor I just added a note with this information and it should be live today. Thank you for your feedback.
