### ISSUE TITLE
Mention the fact that Cache@2 doesn't store the cache if part of a pipeline failed

### ISSUE THREAD

**Issue by timraasveld** [MicrosoftDocs/azure-devops-yaml-schema#241]
The Cache@2 task will not save if part of the pipeline failed. This behavior is not documented by the documentation page, or by the log output of the (post) task. I had to figure this out by [reading this StackOverflow answer](https://stackoverflow.com/a/71920587).

In some use cases, like Docker layer caching, it will still make sense to cache. For example, if a code change resulted in a failing unit test, the Docker cache will still be useful.

Would it make sense to provide advice on what to do in such use cases?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b04ad6d6-d7ee-fc6e-759a-855fa99f1296
* Version Independent ID: b04ad6d6-d7ee-fc6e-759a-855fa99f1296
* Content: [Cache@2 - Cache v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/cache-v2?view=azure-pipelines)
* Content Source: [task-reference/cache-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/cache-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@timraasveld -- Tim, thank you for your feedback.  Please consider this resource:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 

@steved0x -- Steve, please look into this issue.
