### ISSUE TITLE
AzureFunctionApp@2 with runtime JAVA|17

### ISSUE THREAD

**Issue by pradeepgaba01** [MicrosoftDocs/azure-devops-yaml-schema#249]
Does AzureFunctionApp@2  support azure function app deployment with runtime version JAVA|17 ?Could not find this in the documentation 
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-function-app-v2?view=azure-pipelines#syntax

**Comment by WilliamAntonRohm** [comment]
@pradeepgaba01 -- Pradeep, thank you for your question.  Please see these articles:
- https://learn.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=isolated-process%2Cv4&pivots=programming-language-java#languages
- https://learn.microsoft.com/en-us/java/openjdk/support#release-and-servicing-roadmap

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
