### ISSUE TITLE
Default property values

### ISSUE THREAD

**Issue by tor-axbit** [MicrosoftDocs/azure-devops-yaml-schema#25]
Perhaps nitpicking: explicitly showing default property values would reduce ambiguity IMO.

```
autoCancel: boolean 
# Whether to cancel running PR builds 
  when a new commit lands in the branch.  
  Arguments: (false,n,no,off,on,true,y,yes). Default argument: false.
```

---
#### Dokumentinformasjon

⚠ *Ikke rediger denne delen. Den kreves for koblingen docs.microsoft.com ➟ GitHub-problem.*

* ID: cdc780c1-a02a-1dcc-6c18-9363d1566ae2
* Version Independent ID: cdc780c1-a02a-1dcc-6c18-9363d1566ae2
* Content: [pr definition](https://docs.microsoft.com/nb-no/azure/devops/pipelines/yaml-schema/pr?view=azure-pipelines)
* Content Source: [content/pr.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/pr.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@tor-axbit -- thank you for your suggestion.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@steved0x -- Steve, please review this addition in [private PR 55](https://github.com/MicrosoftDocs/azure-devops-yaml-schema-pr/pull/55).

**Comment by steved0x** [comment]
@tor-axbit That is a great suggestion. The YAML blocks are autogenerated from the schema, which doesn't provide any information about the defaults. However we are about to publish an update to this reference, and if these comments become configurable, I will add them. The descriptions in the tables below are configurable once the update is published, and they will appear there. I am going to merge the private PR to get them added now, but when the update publishes, the default info will most likely move out of the YAML block and into the table below. Thank you.
