### ISSUE TITLE
[Manual validation v0 task] Parameter timeoutInMinutes missing in the syntax paragraph

### ISSUE THREAD

**Issue by pierrejeandev** [MicrosoftDocs/azure-devops-yaml-schema#252]
Hello,
I have noticed that the parameter `timeoutInMinutes` is not present in the syntax paragraph.
It is present in the Remark and the example paragraph.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 12456d17-ff9d-eac6-7c70-22fad9bc2a26
* Version Independent ID: 12456d17-ff9d-eac6-7c70-22fad9bc2a26
* Content: [ManualValidation@0 - Manual validation v0 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/manual-validation-v0?view=azure-pipelines)
* Content Source: [task-reference/manual-validation-v0.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/manual-validation-v0.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@pierrejeandev The timeoutInMinutes is part of the common task properties that are present in all tasks. There is a generic section about that in the task inputs, but I will update the article to link to it from the remarks and examples sections. This update will go live today. Thank you.
