### ISSUE TITLE
Hierarchy Markdown

### ISSUE THREAD

**Issue by Rolami** [MicrosoftDocs/azure-devops-yaml-schema#262]
"This hierarchy is reflected in the structure of a YAML file like:

    Pipeline
        Stage A
            Job 1
                Step 1.1
                Step 1.2
                ...
            Job 2
                Step 2.1
                Step 2.2
                ...
        Stage B
            ...
"
This part is written with markdown and is probably confusing to the reader. Should probably either say it's markdown or be a code block. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b85d6c05-acc7-53ec-e452-b0f45c584d62
* Version Independent ID: b85d6c05-acc7-53ec-e452-b0f45c584d62
* Content: [pipeline definition](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/pipeline?view=azure-pipelines)
* Content Source: [content/pipeline.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/pipeline.md)
* Service: **azure-devops-pipelines**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by Rolami** [comment]
Created a pull request that would solve the issue I saw.

**Comment by WilliamAntonRohm** [comment]
@Rolami -- Robin, thank you for your contribution of https://github.com/MicrosoftDocs/azure-devops-yaml-schema/pull/264.
