### ISSUE TITLE
PublishTestResults@2: testResultsFormat is actually not required

### ISSUE THREAD

**Issue by okirmis** [MicrosoftDocs/azure-devops-yaml-schema#263]
For the PublishTestResults@2 task, the docs state in syntax explanation snipped that the `testResultsFormat` property would be required, but it also has a default value (the combination makes little sense):

```yaml
    testResultsFormat: 'JUnit' # 'JUnit' | 'NUnit' | 'VSTest' | 'XUnit' | 'CTest'. Alias: testRunner. Required. Test result format. Default: JUnit.
```

I have tested it and it acutally works when the property is left out (it uses JUnit as the default), so it is actually not required.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fdb3a1b2-9878-405f-bc40-2fb7853cb423
* Version Independent ID: fdb3a1b2-9878-405f-bc40-2fb7853cb423
* Content: [PublishTestResults@2 - Publish Test Results v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-test-results-v2?view=azure-pipelines&tabs=trx%2Ctrxattachments%2Cyaml)
* Content Source: [task-reference/publish-test-results-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/publish-test-results-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
