### ISSUE TITLE
node 18 is supported

### ISSUE THREAD

**Issue by noontz** [MicrosoftDocs/azure-devops-yaml-schema#266]
'NODE|18' should be an option in the docs I believe?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 84a23158-e322-4577-5dcc-de0c380dc186
* Version Independent ID: 84a23158-e322-4577-5dcc-de0c380dc186
* Content: [AzureFunctionApp@1 - Azure Functions v1 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-function-app-v1?view=azure-pipelines)
* Content Source: [task-reference/azure-function-app-v1.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/azure-function-app-v1.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@noontz -- Steffen, thank you for your conjecture.

@steved0x -- Steve, please review this update in [private PR 442](https://github.com/MicrosoftDocs/azure-devops-yaml-schema-pr/pull/442).

**Comment by steved0x** [comment]
@noontz The docs draw the list from the task source code, which is open source here:
https://github.com/microsoft/azure-pipelines-tasks/blob/20629d70d9d6c6c5c587682f5de204e5ba91c120/Tasks/AzureFunctionAppV1/task.json#L118

```
      "options": {
        "DOTNET|2.2": "DOTNET|2.2 (functionapp v2)",
        "DOTNET|3.1": "DOTNET|3.1 (functionapp v3)",
        "DOTNET|6.0": "DOTNET|6.0 (functionapp v4)",
        "JAVA|8": "JAVA|8 (functionapp v2/v3/v4)",
        "JAVA|11": "JAVA|11  (functionapp v3/v4)",
        "NODE|8": "NODE|8 (functionapp v2)",
        "NODE|10": "NODE|10 (functionapp v2/v3)",
        "NODE|12": "NODE|12 (functionapp v3)",
        "NODE|14": "NODE|14 (functionapp v3/v4)",
        "NODE|16": "NODE|16 (functionapp v4)",
        "PYTHON|3.6": "PYTHON|3.6 (functionapp v2/v3)",
        "PYTHON|3.7": "PYTHON|3.7 (functionapp v2/v3/v4)",
        "PYTHON|3.8": "PYTHON|3.8 (functionapp v3/v4)",
        "PYTHON|3.9": "PYTHON|3.9 (functionapp v3/v4)"
      },
```

I am filing an issue there:
https://github.com/microsoft/azure-pipelines-tasks/issues/19394
and if it is added, it will automatically reflect in the task docs. I am also adding a note in the article for that parameter, to emphasize that the list of allowed values is what is suggested in the task assistant for that task, but any value from the supported languages can be used, including `NODE|18`. This update will go live today.
