### ISSUE TITLE
VSTest@3 documentation missing

### ISSUE THREAD

**Issue by quasarea** [MicrosoftDocs/azure-devops-yaml-schema#267]
For a while now VSTest@3 is used as default when creating new vstest step, but there is no documentation on it here.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5a378422-4758-62c7-1793-7ce4724079aa
* Version Independent ID: 5a378422-4758-62c7-1793-7ce4724079aa
* Content: [VSTest@2 - Visual Studio Test v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/vstest-v2?view=azure-pipelines&source=docs)
* Content Source: [task-reference/vstest-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/vstest-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
The new task article will go live today. Than you for letting us know.
