### ISSUE TITLE
Missing documentation for VSTest@3 task

### ISSUE THREAD

**Issue by skeeler** [MicrosoftDocs/azure-devops-yaml-schema#275]
I can find the documentation for VSTest@1 and VSTest@2, but documentation doesn't eppear to exist for VSTest@3 although this task version is showing as available in the repository. Here is the [VSTest@2](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/vstest-v2?view=azure-pipelines) documentation link. Here is the [VSTest@3](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/VsTestV3) task in the repository.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5a378422-4758-62c7-1793-7ce4724079aa
* Version Independent ID: 5a378422-4758-62c7-1793-7ce4724079aa
* Content: [VSTest@2 - Visual Studio Test v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/vstest-v2?view=azure-pipelines)
* Content Source: [task-reference/vstest-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/vstest-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
This will go live today.
