### ISSUE TITLE
need more details on what 'batch' parameter in build pipeline YML means

### ISSUE THREAD

**Issue by charliearcuri** [MicrosoftDocs/azure-devops-yaml-schema#28]
The description for the 'batch' parameter in the "trigger: batch, branches, paths, tags" section is like most code comments. 😊  It just states the obvious... re-reads the variable/parameter name for me. The user's intent when looking up this parameter is to understand what behavior true will produce.  Does the build pipeline wait 20 minutes before starting the build in case other PR's complete in that 20-minute window, so that they can all be integrated ("batched") into a single CI build?  Is it not time-based?

Does "batch" or some other behavior of the pipeline config determine whether multiple runs of the CI build will run concurrently?  For example, if a previous run of the CI build is pending an approval (or something), will new commits be "batched" until the previous "batched" run of the CI build completes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 428d5e92-b3bd-c992-89bf-021bb27233e3
* Version Independent ID: 428d5e92-b3bd-c992-89bf-021bb27233e3
* Content: [trigger definition](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/trigger?view=azure-pipelines)
* Content Source: [content/trigger.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/trigger.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@charliearcuri -- Charlie, thank you for your feedback and questions.

@steved0x -- Steve, please look into this issue.

**Comment by steved0x** [comment]
@charliearcuri Thank you for the feedback. I will add some information about batch to this article. Right now, it will go into the remarks section, but we are about to publish an update that will allow richer content to be integrated into the property descriptions themselves, and when that rolls out, I will add more detail there as well.

When batch is true for a CI trigger, and a pipeline is in a state of running, any subsequent events (pushes) that meet the trigger criteria do not trigger a new run; instead they are "batched" up, and when the currently running pipeline run completes, a new run starts with the "latest" version that includes all of the changes that came in while the pipeline was running.

> Does "batch" or some other behavior of the pipeline config determine whether multiple runs of the CI build will run concurrently? For example, if a previous run of the CI build is pending an approval (or something), will new commits be "batched" until the previous "batched" run of the CI build completes?

That is a good question - one thing that configures whether jobs can run concurrently is how many parallel jobs the organization has. If you only have 1, then only 1 job can run at a time. If you have 5, then up to 5 could run at a time.

If batch is set to true, then only 1 instance of that pipeline will run at a time, even if there is more than 1 parallel job.
If batch is set to false, then multiple instance of that pipeline could run concurrently, up to the limit of parallel jobs available.

I don't know what would happen if a pipeline is blocked waiting for an approval, but I believe it would be in a state of running and if batch is true, new trigger events would not start a new pipeline until the first pipeline completed, at which time a single new run would start. I will test this.

I will add more detail to that article in the meantime. Thank you!
