### ISSUE TITLE
AzureFunctionApp@2 Linux Consumption Plan Deployment fails: ##[error]Error: Unable to find the storage account associated with the function app.

### ISSUE THREAD

**Issue by stu-bell** [MicrosoftDocs/azure-devops-yaml-schema#284]
Deploying to Linux Consumption Plan with AzureFunctionApp@2 fails with the following error: `##[error]Error: Unable to find the storage account associated with the function app.`

Using app setting `AzureWebJobsStorage__accountname` (and managed ID) rather than `AzureWebJobsStorage` as [described here](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/use-managed-identity-instead-of-azurewebjobsstorage-to-connect-a/ba-p/3657606)

It seems that to deploy to a linux consumption plan, you need the `AzureWebJobsStorage` connection string, rather than managed identity and `AzureWebJobsStorage__accountname` setting.

Steps to reproduce: 

1. Create a new function app, Linux, consumption plan.
1. Add app setting with `AzureWebJobsStorage__accountname` name (the value should be the name of the storage account, not the connection string). 
1. Remove the `AzureWebJobsStorage` setting 
1. Enable Managed Identity on the function app
1. In the app's Storage account, grant the `Storage Blob Data Owner` role to the function app 
1. Set up an Azure DevOps pipeline to deploy a sample function app using AzureFunctionApp@2 task
1. Deploy the app code. Pipeline should fail with the error: `##[error]Error: Unable to find the storage account associated with the function app.`
1. Add the app setting `AzureWebJobsStorage` with the value as the storage connection string
1. Redeploy the code pipeline (deployment should succeed)
1. Removing the `AzureWebJobsStorage` setting should still allow the function app to run (assuming you still have the `AzureWebJobsStorage__accountname` setting) but you won't be able to redeploy. 

Deploying to a Windows Consumption app, or a Linux premium/dedicated app, doesn't seem to require the connection string and deploying with `AzureWebJobsStorage__accountname` just works (appears that for windows consumption, the Storage Account Key must be enabled, even if the connection string is not used). Could be something to do with `WEBSITE_RUN_FROM_PACKAGE` setting requires a URL for Linux Consumption plans but not the others?

Ideally, the devops task should be updated to support deployment to linux consumption plans that use the `AzureWebJobsStorage__accountname` setting rather than the connection string. 

Until that's possible, the [documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-function-app-v2?view=azure-pipelines#troubleshooting) should be updated to include the error: 

```
Unable to find the storage account associated with the function app: 

You may encounter this error if you are deploying to a Linux Consumption plan and are using AzureWebJobsStorage__accountname setting instead of AzureWebJobsStorage. 

Use AzureWebJobsStorage connection string instead of accountname. Or change the app to a Windows Consumption plan, or use a Linux Premium or Dedicated plan.
```

Note: I originally noticed this error using a python function app. Python is unsupported on Windows so I also tested with a node app. When deploying a node function app to Linux consumption plan using the __accountname setting, I received a generic 400 error in the devops pipeline, which was fixed by adding the connection string setting. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 87b190ff-4ca4-a7ca-381d-e97185d05df1
* Version Independent ID: 87b190ff-4ca4-a7ca-381d-e97185d05df1
* Content: [AzureFunctionApp@2 - Azure Functions Deploy v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-function-app-v2?view=azure-pipelines)
* Content Source: [task-reference/azure-function-app-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/azure-function-app-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@stu-bell -- Stuart, thank you for your well-researched feedback.

@steved0x -- Steve, please look into this issue.

**Comment by reubano** [comment]
I'm facing the same issue.

**Comment by knguyen4221** [comment]
Also facing this issue.

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
