### ISSUE TITLE
Does AzureWebAppContainer@1 support Workload Identity Federation authentication scheme?

### ISSUE THREAD

**Issue by cyclelabs-ryanberger** [MicrosoftDocs/azure-devops-yaml-schema#287]
We are migrating our Azure DevOps Service Connections over to WIF's and ran into an issue with some tasks not supporting them - like AzureFileCopy. I wanted to ask if this Task will allow a WIF service connection to authenticate and then deploy to my Azure Web Apps?

Thanks a ton!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d4ef50dd-21c3-7cae-90bf-b5bc059fa512
* Version Independent ID: d4ef50dd-21c3-7cae-90bf-b5bc059fa512
* Content: [AzureWebAppContainer@1 - Azure Web App for Containers v1 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-web-app-container-v1?view=azure-pipelines)
* Content Source: [task-reference/azure-web-app-container-v1.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/azure-web-app-container-v1.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
