### ISSUE TITLE
The lastestVersion of AzurePowerShell on this task is extremely outdated

### ISSUE THREAD

**Issue by handrade-xom** [MicrosoftDocs/azure-devops-yaml-schema#290]
WARNING: You're using Az version 9.3.0. The latest version of Az is 11.2.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5de2083f-ba71-fce1-ec99-91ee90d0d001
* Version Independent ID: 5de2083f-ba71-fce1-ec99-91ee90d0d001
* Content: [AzurePowerShell@5 - Azure PowerShell v5 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-powershell-v5?view=azure-pipelines)
* Content Source: [task-reference/azure-powershell-v5.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/azure-powershell-v5.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
