### ISSUE TITLE
No docs for VSTest@3

### ISSUE THREAD

**Issue by Tiberriver256** [MicrosoftDocs/azure-devops-yaml-schema#291]
Hello,

There are docs for VSTest@1 and VSTest@2 but the latest version VSTest@3 has no documentation available.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5a378422-4758-62c7-1793-7ce4724079aa
* Version Independent ID: 5a378422-4758-62c7-1793-7ce4724079aa
* Content: [VSTest@2 - Visual Studio Test v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/vstest-v2?view=azure-pipelines)
* Content Source: [task-reference/vstest-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/vstest-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
This will be live today.

**Comment by Tiberriver256** [comment]
Thank you!
