### ISSUE TITLE
maxParallel/parallel should be integer, not string?

### ISSUE THREAD

**Issue by QuLogic** [MicrosoftDocs/azure-devops-yaml-schema#293]
In the [`strategy: matrix, maxParallel` section](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/jobs-job-strategy?view=azure-pipelines#strategy-matrix-maxparallel), the `maxParallel` key is typed as string, even though all descriptions of it call it a "number". In the [`strategy: parallel` section](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/jobs-job-strategy?view=azure-pipelines#strategy-parallel), the `parallel` key is also typed as string.

Weirdly, the [first `Remarks` section](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/jobs-job-strategy?view=azure-pipelines#remarks) has a _second_ copy of the typing, but has `maxParallel` as a `number` (but the second `Remarks` doesn't have the repeated typing.)

The examples on this page though, give `maxParallel`/`parallel` as an integer (i.e., `4` or `2`), not a string. For schema purposes, it seems like `maxParallel`/`parallel` should be changed from `string` to `integer`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 38aa6313-3818-cb19-e06d-8e52364f992b
* Version Independent ID: 38aa6313-3818-cb19-e06d-8e52364f992b
* Content: [jobs.job.strategy definition](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/jobs-job-strategy?view=azure-pipelines)
* Content Source: [content/jobs-job-strategy.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/jobs-job-strategy.md)
* Service: **azure-devops-pipelines**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
