### ISSUE TITLE
Incorrect definition of valid values of job ID

### ISSUE THREAD

**Issue by Michaelvsk** [MicrosoftDocs/azure-devops-yaml-schema#3]
Hi,
the documentation specifies that a job ID may consist of these characters `[-_A-Za-z0-9]*`.
When using `TF-Plan-DEV` as the ID the Azure DevOps Services Portal complains with the following error message:

> Stage DEV job TF-Plan-DEV has an invalid name. Valid names may only contain alphanumeric characters and '_' and may not start with a number.

So I suggest these improvements:
1. Hyphens `-` aren't allowed.
2. ID may not start with a number (underscore is allowed indeed - just have checked it).

I suggest to update the documentation to use this regex `^[_a-zA-Z][_a-zA-Z0-9]*$` or in shorter form `^[_a-zA-Z][\w]*$`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec6c0374-c5cb-82b7-860a-464a1037df61
* Version Independent ID: ec6c0374-c5cb-82b7-860a-464a1037df61
* Content: [jobs.job definition](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/jobs-job?view=azure-pipelines)
* Content Source: [content/jobs-job.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/jobs-job.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@Michaelvsk Thank you for letting us know. The documentation automatically picks up the regular expression from the json schema that is used to validate in the YAML Pipeline editor. I can fix this issue in our documentation and I will file a bug internally on the schema.
