### ISSUE TITLE
agentLocation - Test agent location - Install Test Agent 2017 points to the 2015 version

### ISSUE THREAD

**Issue by hunyu** [MicrosoftDocs/azure-devops-yaml-schema#301]
Under
agentLocation - Test agent location
string.

Optional. Supplies the path to vstf_testagent.exe from the network or local location. If no path is provided, it will be automatically downloaded from the [download center](https://go.microsoft.com/fwlink/?LinkId=827840). [Install the Test Agent 2015 Update 3](https://go.microsoft.com/fwlink/?LinkId=827840).
[Install Test Agent 2017](https://aka.ms/vs/15/release/vs_TestAgent.exe) <== You can it actually points to the one from 2015

Expected to 
[Install Test Agent 2017](https://aka.ms/vs/17/release/vs_TestAgent.exe)
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b0300052-f5c1-5edc-3a9c-1b9996e1fe2c
* Version Independent ID: b0300052-f5c1-5edc-3a9c-1b9996e1fe2c
* Content: [DeployVisualStudioTestAgent@2 - Visual Studio test agent deployment v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/deploy-visual-studio-test-agent-v2?view=azure-pipelines)
* Content Source: [task-reference/deploy-visual-studio-test-agent-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/deploy-visual-studio-test-agent-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
*

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
