### ISSUE TITLE
UseDotNet@2 task should clarify that global.json file contents are largely ignored

### ISSUE THREAD

**Issue by kevcrooks** [MicrosoftDocs/azure-devops-yaml-schema#303]
In the documentation page for the task it says
"For more information on global.json, see [Select the .NET version to use](https://learn.microsoft.com/en-us/dotnet/core/versions/selection)."

This appears to indicate that the task would use the global.json file as specified. However it appears that the task only uses the "version" property of the global.json file and ignores other properties (such as "rollForward"), as I think this comment in the pipeline task itself is indicating:
https://github.com/microsoft/azure-pipelines-tasks/issues/19292#issuecomment-1831304847

This is _extremely_ misleading (and left me confused for a long time). So if this is the case, can these limitations in the global.json support be clarified in the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a9c6264c-6eed-8e94-0d93-47983e69060c
* Version Independent ID: a9c6264c-6eed-8e94-0d93-47983e69060c
* Content: [UseDotNet@2 - Use dotnet v2 task](https://learn.microsoft.com/en-gb/azure/devops/pipelines/tasks/reference/use-dotnet-v2?view=azure-pipelines&viewFallbackFrom=azure-devops)
* Content Source: [task-reference/use-dotnet-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/use-dotnet-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
