### ISSUE TITLE
CocoaPods@0 - Upgrade CocoaPods version 1.15.2

### ISSUE THREAD

**Issue by djhr** [MicrosoftDocs/azure-devops-yaml-schema#304]
Current CocoaPods@0 task uses cocoapods version 1.15.0, which has issues installing hermes-engine from react-native.

A fix for this issue is available in version 1.15.2, you can find more details of the issue on https://github.com/CocoaPods/CocoaPods/issues/12226

Ideally this task would receive the cocoapods version as input, to empower users overcoming issues/blockers like this.

**Comment by WilliamAntonRohm** [comment]
@djhr -- thank you for your feedback.

@steved0x -- I'm not sure whether this is a documentation issue or a task coding issue.  The article is:
- [CocoaPods@0 - CocoaPods v0 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/cocoa-pods-v0?view=azure-pipelines)

**Comment by GSFZamai** [comment]
Hi there, same issue here. Getting error when going to install pods with Azure Pipelines.
Agreed with @djhr , would be nice if we can specify the cocoapods version.

**Comment by MinskLeo** [comment]
Hi guys. Same issue, so I’m also joining the discussion - it would be cool to be able to choose cocoapods version.

**Comment by matiaswastaken** [comment]
Hi, we are also currently running into this same problem using React Native and cocoapods task.

Would appreciate a way to manually set version or if you could at least bump the version up to 1.15.2 to fix this.

**Comment by nirodhaperera-ifs** [comment]
Hi, we are facing the same issue. 
Any update on this @WilliamAntonRohm @steved0x ?

**Comment by JasonPan** [comment]
As a temporary workaround, this script works for me to get the tooling updated to resolve the [issue](https://github.com/CocoaPods/CocoaPods/issues/12226)

```bash
brew update

brew uninstall cocoapods

sudo gem uninstall cocoapods
sudo gem uninstall -n /usr/local/bin cocoapods

brew install cocoapods
```

**Comment by GSFZamai** [comment]
Until friday, when I rerun the failed job the cocoapods version change and the build succeeded. But today the cocoapods version persists on 1.15.0...

**Comment by djhr** [comment]
@steved0x do you have an update on this issue?

**Comment by GSFZamai** [comment]
> As a temporary workaround, this script works for me to get the tooling updated to resolve the [issue](https://github.com/CocoaPods/CocoaPods/issues/12226)
> 
> ```shell
> brew update
> 
> brew uninstall cocoapods
> 
> sudo gem uninstall cocoapods
> sudo gem uninstall -n /usr/local/bin cocoapods
> 
> brew install cocoapods
> ```

This resolved the issue for now.

```yaml
- script: |
          brew update
          brew uninstall cocoapods
          gem uninstall cocoapods --ignore-dependencies
          sudo gem uninstall -n /usr/local/bin cocoapods
          gem install cocoapods -v 1.15.2
        displayName: 'Update cocoapods'
```

**Comment by djhr** [comment]
@WilliamAntonRohm any update on this? It's been a month since we've reported this blocking issue on Azure DevOps pipelines and still no foreseeable action on Microsoft side.

This is not a documentation issue, at the moment it's not possible to install pods from react-native on Azure DevOps pipelines, this affects every single Microsoft customer trying to install it.

Would it be possible to raise the priority of this issue, please?

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
