### ISSUE TITLE
Tip about Visual Studio being 32 bit is incorrect - VS 2022 is 64 bit

### ISSUE THREAD

**Issue by andrewimcclement** [MicrosoftDocs/azure-devops-yaml-schema#305]
The tip about VS being a 32 bit application isn't correct any more - VS 2022 is 64 bit, so it could be changed to say something specifying VS2019 or older.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 83462061-cbc6-ae80-bd84-65a7f61c319b
* Version Independent ID: 83462061-cbc6-ae80-bd84-65a7f61c319b
* Content: [VSBuild@1 - Visual Studio build v1 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/vsbuild-v1?view=azure-pipelines)
* Content Source: [task-reference/vsbuild-v1.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/vsbuild-v1.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
