### ISSUE TITLE
Restore and push remarks unclear

### ISSUE THREAD

**Issue by Stephen-Bethke** [MicrosoftDocs/azure-devops-yaml-schema#309]
In the 'Important' note you specify, "The restore and push commands of this .NET Core CLI task no longer take new features and only critical bugs are addressed. See remarks for details."

The remarks section just repeats this statement, but the statement itself seems to imply that there is a newer, better way to do restore and push.  There is no other mention of this anywhere in the remarks section that I can find. So does this mean that restore and push are perfect, and no longer need changes, or is there another way?

Therefore, please could you clarify what you mean by saying that there will be no new features and only critical bugs are address.

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5825539f-634b-03d6-35f0-b532177a5e3b
* Version Independent ID: 5825539f-634b-03d6-35f0-b532177a5e3b
* Content: [DotNetCoreCLI@2 - .NET Core v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/dotnet-core-cli-v2?view=azure-pipelines#remarks)
* Content Source: [task-reference/dotnet-core-cli-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/dotnet-core-cli-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
