### ISSUE TITLE
DependsOn, condition and variables with stage template

### ISSUE THREAD

**Issue by adeliab** [MicrosoftDocs/azure-devops-yaml-schema#31]
Are there more advanced examples on this?
Like setting dependsOn, condition and variables in the stage template?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49ed15b8-f956-4839-5caa-611f69f207b7
* Version Independent ID: 49ed15b8-f956-4839-5caa-611f69f207b7
* Content: [stages.template definition](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/stages-template?view=azure-pipelines)
* Content Source: [content/stages-template.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/stages-template.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
