### ISSUE TITLE
Add 'PYTHON|3.11' to runtimeStack input, in AzureFunctionApp@2 documentation

### ISSUE THREAD

**Issue by isakengstrom** [MicrosoftDocs/azure-devops-yaml-schema#311]
Python 3.11 is supported by the AzureFunctionApp@2 task, but it's missing in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 87b190ff-4ca4-a7ca-381d-e97185d05df1
* Version Independent ID: 87b190ff-4ca4-a7ca-381d-e97185d05df1
* Content: [AzureFunctionApp@2 - Azure Functions Deploy v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-function-app-v2?view=azure-pipelines)
* Content Source: [task-reference/azure-function-app-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/azure-function-app-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by Saulopv** [comment]
Does the runtimeStack work for updating the language version?

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
