### ISSUE TITLE
Task Delay and waiting over 1 hour

### ISSUE THREAD

**Issue by Bouke** [MicrosoftDocs/azure-devops-yaml-schema#312]
> Delays the execution of the workflow by specified time in minutes. A 0 value means that workflow execution will start without delay. The maximum value is 86400 (60 days).

The page fails to mention a job's default timeout duration of 1 hour. Even though the maximum is 60 days, waiting for over 1 hour fails by default:

```
- task: Delay@1
  inputs:
    delayForMinutes: 120
```

It would be helpful to mention a job's `timeoutInMinutes` here.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 00d9533b-ac17-be91-f1fe-e90e4185d960
* Version Independent ID: 00d9533b-ac17-be91-f1fe-e90e4185d960
* Content: [Delay@1 - Delay v1 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/delay-v1?view=azure-pipelines)
* Content Source: [task-reference/delay-v1.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/delay-v1.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
