### ISSUE TITLE
[UploadTestResults@2] JUnit mapping documentation inconsistent with observed behavior

### ISSUE THREAD

**Issue by Erich-McMillan** [MicrosoftDocs/azure-devops-yaml-schema#313]
# Issue

[Documentation](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/publish-test-results-v2.md#junit) suggests that `Test Run Title` may only be populated via `Test run title specified in the task`. However, if a junit xml file sets the attribute `/testsuites/testsuite.Attributes["Name"].Value` then that value is used only when `Test Run Title` input is not provided.

## Expected Result

This behavior is expected and appreciated but should be documented. I believe the change should be:

```diff
#### [JUnit](#tab/junit)

| Scope | Field | JUnit |
|-|-|-|
---| [**Test run**](/azure/devops/pipelines/test/test-glossary) | Title | **Test run title** specified in the task |
+++| [**Test run**](/azure/devops/pipelines/test/test-glossary) | Title | **Test run title** specified in the task or /testsuites/testsuite.Attributes["Name"].Value if Test run title is not provided in the task |
|  | Date started | /testsuites/testsuite.Attributes["**timestamp**"].Value |
|  | Date completed | /testsuites/testsuite.Attributes["**timestamp**"].Value + SUM(/testsuites/testsuite/testcase.Attributes["**time**"].Value) for all test cases in the test suite |
|  | Duration | Date completed - Date started |
```
## How to Repro

Sample JUnit:
```xml
<testsuite name="testsuite1" tests="1" errors="0" failures="0" skipped="0" time="7.963" timestamp="2024-02-24 20:16:28.426214">
	<testcase classname="testsuite1.py" name="Test1" result="Pass" time="0:00:00.001093" />
</testsuite>
```

Sample pipeline yaml:
```yaml
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/Test.xml'
    searchFolder: "$(Build.SourcesDirectory)"
```

## Result
<img width="752" alt="image" src="https://github.com/MicrosoftDocs/azure-devops-yaml-schema/assets/17664632/f20aa24e-15a6-4dd6-86bf-bda86e2a0647">

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
