### ISSUE TITLE
How to cancel Delay task?

### ISSUE THREAD

**Issue by Bouke** [MicrosoftDocs/azure-devops-yaml-schema#314]
How can I cancel a Delay task [without workarounds](https://stackoverflow.com/questions/72495333/delay-task-in-azure-pipeline-cannot-be-cancelled)?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 00d9533b-ac17-be91-f1fe-e90e4185d960
* Version Independent ID: 00d9533b-ac17-be91-f1fe-e90e4185d960
* Content: [Delay@1 - Delay v1 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/delay-v1?view=azure-pipelines)
* Content Source: [task-reference/delay-v1.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/delay-v1.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@Bouke -- Bouke, thank you for your feedback.  Please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)
