### ISSUE TITLE
downloadType documentation is switched around

### ISSUE THREAD

**Issue by Kurren123** [MicrosoftDocs/azure-devops-yaml-schema#316]
Right now it says:

```
Choose single (Specific artifact) when you want only one specific artifact specified by artifactName
Choose specific (Specific files) when you want all artifacts of the selected build
```

But it should be the other way around

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 183cc246-bc10-29ba-63a3-1608007c7e9d
* Version Independent ID: 183cc246-bc10-29ba-63a3-1608007c7e9d
* Content: [DownloadBuildArtifacts@1 - Download build artifacts v1 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/download-build-artifacts-v1?view=azure-pipelines)
* Content Source: [task-reference/download-build-artifacts-v1.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/download-build-artifacts-v1.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
