### ISSUE TITLE
Info about Linux not being supported should be more visible

### ISSUE THREAD

**Issue by vanmash** [MicrosoftDocs/azure-devops-yaml-schema#317]
Information that this task is not supported on Linux should be put in bold at the beginning of the page.

Also it *should* be supported on Linux, it is not 1995 anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ddb32280-1779-eb6e-0f78-8707be623a9a
* Version Independent ID: ddb32280-1779-eb6e-0f78-8707be623a9a
* Content: [SqlAzureDacpacDeployment@1 - Azure SQL Database deployment v1 task](https://learn.microsoft.com/en-gb/azure/devops/pipelines/tasks/reference/sql-azure-dacpac-deployment-v1?view=azure-pipelines)
* Content Source: [task-reference/sql-azure-dacpac-deployment-v1.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/sql-azure-dacpac-deployment-v1.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
