### ISSUE TITLE
Has the default behaviour for checkout changes?

### ISSUE THREAD

**Issue by ChrisSidebotham** [MicrosoftDocs/azure-devops-yaml-schema#32]
Upon creating new pipelines since 1/9/2022 the checkout behaviour in Azure DevOps is only doing a git fetch on the ref spec of the current branch. We do not specify any additional parameters just `checkout: Self` as evidenced here:
Checkout task in pipeline:
```    steps:
      - checkout: self
```
Output from line 33 in checkout task:
`git --config-env=http.extraheader=env_var_http.extraheader fetch --force --tags --prune --prune-tags --progress --no-recurse-submodules origin --depth=1 +<HashValue>:refs/remotes/origin/<HashValue>
`

Exploration of this issue has led to finding that adding `fetchDepth: 0` returns the checkout task to normal behaviour as shown below:
Checkout task in pipeline:
```
    steps:
      - checkout: self
        fetchDepth: 0
```

Output from line 33 in checkout task: 
`git --config-env=http.extraheader=env_var_http.extraheader fetch --force --tags --prune --prune-tags --progress --no-recurse-submodules origin
`

The current expected behaviour of a script that runs as part of the pipeline, looks to do a Git Diff with origin/main. following the recent changes this behaviour has stopped working resulting in a breaking change. This behaviour is only for newly created pipelines and not for existing pipelines already configured in ADO. The default value of 'git fetch' is not published in this documentation to cross reference.

Note: Hash values have been redacted from the output.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b28abf7f-ecdf-8037-acd9-722690424372
* Version Independent ID: b28abf7f-ecdf-8037-acd9-722690424372
* Content: [steps.checkout definition](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelines)
* Content Source: [content/steps-checkout.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/steps-checkout.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@ChrisSidebotham Let me look into this and see if something has changed.

**Comment by mvromer** [comment]
I am seeing this exact behavior as well. I created a new pipeline this morning, and I've noticed that for new pipelines, the fetch depth is getting set to one as evidenced by the `--depth=1` argument added to the `git fetch` command when inspecting the pipeline's checkout step. In my case, I don't specify a checkout step and just use the one that Azure Pipelines implicitly adds.

When I re-run existing pipelines, including those I just made last month, their checkout steps do not include the `--depth=1` argument during the git fetch command.

If the default behavior has indeed changed, it's definitely a breaking one. In my situation, I use [GitVersion](https://gitversion.net/) to help automatically figure out version numbers for new packages I'm building, and it needs to be able to walk the commit history to find version bump tags in the commit messages. When fetch depth is set to 1, this pretty much breaks the version calculation.

While I can workaround this by coding my own checkout step, it does mean touching a number of pipeline configurations and templates that we're leveraging in-house. At the very least, having things like the default fetch depth documented would be good.

**Comment by odelljl** [comment]
I have observed the same problem. It is also tripping up my subsequent steps that use gitversion to calculate the semantic version of my build. This is occurring on new builds - although I am referencing the same YAML template in older builds. 

My git repository is new as well - there may is something in the new repository process that, in turn, is causing the behavior in pipelines.

In my case the following line in the log has changed:

Original: 

```log
##[command]git --config-env=http.extraheader=env_var_http.extraheader fetch --force --tags --prune --prune-tags --progress --no-recurse-submodules origin
```

Failing:

```log
##[command]git --config-env=http.extraheader=env_var_http.extraheader fetch --force --tags --prune --prune-tags --progress --no-recurse-submodules origin --depth=1 +c80b4ef1b938802a0f19ed824a8237d477c71618:refs/remotes/origin/c80b4ef1b938802a0f19ed824a8237d477c71618
```

**Comment by AArnott** [comment]
I just confirmed this in my own AzDO account too. Pretty lame that this decision was made silently and not documented anywhere that we can find. :(

I'll document on Nerdbank.GitVersioning that folks need to change their pipelines to defeat shallow clones to keep working.

**Comment by steved0x** [comment]
@ChrisSidebotham @mvromer @odelljl @AArnott It looks like the "Shallow fetch" setting may have been turned on by default for newer pipelines. There is a ticket opened up here for tis issue:

https://developercommunity.visualstudio.com/t/checkout-step-adds---depth1-even-if-not/10144373?space=21&q=checkout+depth

Please go and upvote this issue, the more votes it has, the higher priority it gets.

In the meantime, I will try and find out what/when this happened, and add a callout to this documentation.

**Comment by RomanDvorsky** [comment]
Hi, 

I agree that making breaking changes without noticing is quite lame amateur approach - this breaking change destroys our gitversion.

Here is a workaround how to turn off this great feature for given pipeline:

1. Edit pipeline
2. click ... (3 dots button)
3. go to triggers
4. go to yaml
5. click get sources
6. uncheck 'shallow fetch'

![image](https://user-images.githubusercontent.com/36188474/191899379-f85fdca6-6a24-41b8-9fc6-0fbc08df8ac5.png)

**Comment by steved0x** [comment]
This has been added to the documentation and should be live shortly.

https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelines#remarks

https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#shallow-fetch

Thank you for letting us know.

**Comment by odelljl** [comment]
Looks great! Thanks - jlo
________________________________

**Comment by edwardskrod** [comment]
Thanks for documenting this.  Just ran into it also.
