### ISSUE TITLE
PublishCodeCoverageResults@2 add details that it will only supports generating Lines coverage 

### ISSUE THREAD

**Issue by Exact-RolfvanKuijen** [MicrosoftDocs/azure-devops-yaml-schema#321]
In the documentation please add that PublishCodeCoverageResults@2 only supports lines coverage and not others forms like blocks, branches, custom (methods). Nor will the overview created show such information.
This means those who are still using PublishCodeCoverageResults@1 who do not use lines coverage cannot migrate and will have to keep using that version.
This is especially needed for those to avoid breaking when using BuildQualityChecks.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: faca1d26-d98d-e263-da8b-0bc97896b69c
* Version Independent ID: faca1d26-d98d-e263-da8b-0bc97896b69c
* Content: [PublishCodeCoverageResults@2 - Publish code coverage results v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-code-coverage-results-v2?view=azure-pipelines)
* Content Source: [task-reference/publish-code-coverage-results-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/publish-code-coverage-results-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by mdenhoedt** [comment]
Any update on this? Very confusing to let version 1 generate a warning, and version 2 not being mature.

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
