### ISSUE TITLE
How to run a script the right way?

### ISSUE THREAD

**Issue by sliekens** [MicrosoftDocs/azure-devops-yaml-schema#325]
Hello,

I'm a bit puzzled why there are so many different ways to just run a Bash script. There is `steps.script`, `steps.bash` and multiple tasks that seem to do the same thing, differently. Is this clarified anywhere?

- https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/cmd-line-v2?view=azure-pipelines
    - shortcut available as steps.script
    - https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-script?view=azure-pipelines
- https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/shell-script-v2?view=azure-pipelines
   - shortcut available as steps.bash
   - https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-bash?view=azure-pipelines 
- https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/bash-v3?view=azure-pipelines
   - no shortcut available

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 18090cba-5cc1-9d3d-8de0-44e0eee0215f
* Version Independent ID: 18090cba-5cc1-9d3d-8de0-44e0eee0215f
* Content: [Bash@3 - Bash v3 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/bash-v3?view=azure-pipelines)
* Content Source: [task-reference/bash-v3.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/bash-v3.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
