### ISSUE TITLE
Note when “addSpnToEnvironment” does not populate the “servicePrincipalKey” variable.

### ISSUE THREAD

**Issue by AvinZarlez** [MicrosoftDocs/azure-devops-yaml-schema#326]
The `addSpnToEnvironment` flag for Azure CLI DevOps task does not populate the `servicePrincipalKey` variable unless the Azure Resource Manager connection is a Service Principle.

When using a managed identity, `servicePrincipalId` and `tenantId` are set but a `servicePrincipalKey` is not. If you need a  `servicePrincipalKey`, you need to make sure that you use a Azure Service Principle connection in the Azure Resource Manager.

Ran into an issue setting up a DevOps pipeline for a customer, and it wasn't clear what it was. Adding some clarity to the documentation here would help

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed2fb7c-dd4c-7d2a-a934-e86bc5c1aa5d
* Version Independent ID: 3ed2fb7c-dd4c-7d2a-a934-e86bc5c1aa5d
* Content: [AzureCLI@2 - Azure CLI v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-cli-v2?view=azure-pipelines)
* Content Source: [task-reference/azure-cli-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/azure-cli-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
