### ISSUE TITLE
Broken SSH@0 task for older on-prem agents

### ISSUE THREAD

**Issue by timonviola** [MicrosoftDocs/azure-devops-yaml-schema#327]
Hi

I believe that the `Requirements` part of the docs are not updated:

Running an on-prem agent (version 2.202.0), SSH@0 (version:  0.236.2) task fails with the following message:
` ##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.`

SSH@0 version 0.231.3 was working with the agent before. Updating the agent fixed the issue, please [also see my comment](https://developercommunity.visualstudio.com/t/The-current-operating-system-is-not-capa/10616580#T-N10618270). 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 22bbc26f-0519-e5af-b8f8-8bfd9f8b63df
* Version Independent ID: 22bbc26f-0519-e5af-b8f8-8bfd9f8b63df
* Content: [SSH@0 - SSH v0 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/ssh-v0?view=azure-pipelines)
* Content Source: [task-reference/ssh-v0.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/ssh-v0.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
