### ISSUE TITLE
Artifacts are no longer downloaded to a subfolder with the artifactName

### ISSUE THREAD

**Issue by donnie-msft** [MicrosoftDocs/azure-devops-yaml-schema#329]
When my pipeline used `DownloadBuildArtifacts`, those artifacts went into a new subfolder named `artifactName` in the `downloadPath`. 
When switching to `PublishPipelineArtifact`, the artifacts go into `downloadPath` but not into a new subfolder.

This discrepancy should be documented. Since we have scripts looking for artifacts in a particular folder, those scripts fail to find a subfolder with the artifact name.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6d5753b5-d4e7-6696-0230-3595f632ba0e
* Version Independent ID: 6d5753b5-d4e7-6696-0230-3595f632ba0e
* Content: [DownloadPipelineArtifact@2 - Download Pipeline Artifacts v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/download-pipeline-artifact-v2?view=azure-pipelines)
* Content Source: [task-reference/download-pipeline-artifact-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/download-pipeline-artifact-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
