### ISSUE TITLE
Document that TestResultsPublisher.exe is the underlying workhorse and the hosts it needs access to.

### ISSUE THREAD

**Issue by zippy1981** [MicrosoftDocs/azure-devops-yaml-schema#33]
There are a large list of hosts one must allow for all functionality of a TFS build agent to work.

As noted [here](https://developercommunity.visualstudio.com/t/TestResultspublisherexe-does-not-report/10141301?space=21&q=TestResultsPublisher.exe&entry=problem) for publishing test results you only seem to need two of them.

For the sake of easing troubleshooting please note that TestResultsPublisher.exe is called by this task and that the agent it runs on needs access to https://*vstmrblob.vsassets.io and https://*.vstmr.visualstudio.com specifically.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdb3a1b2-9878-405f-bc40-2fb7853cb423
* Version Independent ID: fdb3a1b2-9878-405f-bc40-2fb7853cb423
* Content: [PublishTestResults@2 - Publish Test Results v2 task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-test-results-v2?view=azure-pipelines&viewFallbackFrom=azure-devops&tabs=trx%2Ctrxattachments%2Cyaml)
* Content Source: [task-reference/publish-test-results-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/publish-test-results-v2.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
