### ISSUE TITLE
PublishSymbols default SearchPattern (and doc) is a poor choice leading to not being able to analyze crashes and other reliability issues

### ISSUE THREAD

**Issue by ivberg** [MicrosoftDocs/azure-devops-yaml-schema#330]
SearchPattern in PublishSymbols@2 has a bad default that will result in not able to properly analyze Reliability issues including crashes, hangs, memory leaks, etc. Since the ability to analyze is the MAIN purpose of publishing symbols, this is clearly a bad default.

I even worked in the crashdump analysis area for Microsoft, and did not realize right away these were poor defaults, until I was not able to analyze crash dumps for my own process.

Backstory: Almost all modern binaries x64, arm64, .NET REQUIRE binaries (.exe, .dll) to also be uploaded to the symbol server along with .pdbs files. Without these files, stack unwinding cannot happen and analysis will be messed up in WinDbg, VS, or other analysis tools.

SearchPattern - Search pattern
string. Required. Default value: **/bin/**/*.pdb  <--- Bad default

Specifies the pattern used to discover the PDB files to publish. See [File matching patterns reference](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns) for more information.

The task defaults for PublishSymbols and docs should change to this which properly publish symbols for all 3 file types. 
```
            SearchPattern: |
              **/bin/**/*.pdb
              **/bin/**/*.exe
              **/bin/**/*.dll
```

Also, this SearchPattern syntax is not intuitive if you read the file matching pattern docs. I got it wrong the first time resulting in no files published

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4d97490d-94e9-7c19-f87a-0594ff604c3e
* Version Independent ID: 4d97490d-94e9-7c19-f87a-0594ff604c3e
* Content: [PublishSymbols@2 - Index sources and publish symbols v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-symbols-v2?view=azure-pipelines)
* Content Source: [task-reference/publish-symbols-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/publish-symbols-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by ivberg** [comment]
Product issue: https://github.com/microsoft/azure-pipelines-tasks/issues/19691

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
