### ISSUE TITLE
Document not updated about - task: SonarQubePrepare@6

### ISSUE THREAD

**Issue by arsalanzvl** [MicrosoftDocs/azure-devops-yaml-schema#344]
- task: SonarQubePrepare@6
Sonar has released a new version for sonar task, its mentioned in their documentation [SonarQube Doc](https://docs.sonarsource.com/sonarqube/10.4/devops-platform-integration/azure-devops-integration/?_gl=1*nfzich*_gcl_au*MjEzMTMwNDA0Mi4xNzEzMjU3ODE2*_ga*NDg4NzQzMDAuMTcwNTM4OTc4Mg..*_ga_9JZ0GZ5TC6*MTcxODAxODc5MC41MC4xLjE3MTgwMTkxOTIuNjAuMC4w#steps-to-construct-your-azure-pipeline) but not in Microsoft's,

**Comment by alexravenna** [comment]
A page for version 6 of the task has been added in the meantime:
- [commit](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/commit/c2a6689cff0260ac2c667a8643e2a6137f1674ed#diff-c9a7d15a82adb6a373f0a80e6d9e70438205e8f4e90fa6b3353161478c5e7be4)
- [source file](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/sonar-qube-prepare-v6.md)
- [published page](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/sonar-qube-prepare-v6)

**Comment by steved0x** [comment]
The new tasks for the SonarCube v 6 tasks are live now.
