### ISSUE TITLE
Missing `name`  property to docs page for repository keyword

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/azure-devops-yaml-schema#4]
The example shows a property named `name`, but that is not part of the description above.

▶ Let's either correct the example or add the missing property to this page.

Thanks!
--Neno

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fb0ba85-0e96-cb7a-6984-0ab15823ea32
* Version Independent ID: 9fb0ba85-0e96-cb7a-6984-0ab15823ea32
* Content: [resources.repositories.repository definition](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/resources-repositories-repository?view=azure-pipelines&WT.mc_id=DOP-MVP-21138#examples)
* Content Source: [content/resources-repositories-repository.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/resources-repositories-repository.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
#investigating

**Comment by steved0x** [comment]
@NenoLoje Thank you for letting us know - this will be fixed today.
