### ISSUE TITLE
Should document that fetchDepth defaults to 0

### ISSUE THREAD

**Issue by odelljl** [MicrosoftDocs/azure-devops-yaml-schema#45]
There was a recent change to update the default of the fetchDepth to 0. This broke some pipelines for customers that depended on fetching the entire repository for evaluation bu tools like gitversion. The default should be documented here.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b28abf7f-ecdf-8037-acd9-722690424372
* Version Independent ID: b28abf7f-ecdf-8037-acd9-722690424372
* Content: [steps.checkout definition](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelines)
* Content Source: [content/steps-checkout.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/steps-checkout.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
This has been added to the documentation and should be live shortly.

https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelines#remarks

https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#shallow-fetch

Thank you for letting us know.
