### ISSUE TITLE
"Predefined variables" section is misleading

### ISSUE THREAD

**Issue by petrkoutnycz** [MicrosoftDocs/azure-devops-yaml-schema#5]
The section called "The pipeline resource metadata as predefined variables" is kind of misleading as it refers to a "Alias" property which is unknown. There are just properties "pipeline" and "source" that seems to be valid for the context.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb60190b-fc26-9eb2-70c3-a8b1a0227658
* Version Independent ID: bb60190b-fc26-9eb2-70c3-a8b1a0227658
* Content: [resources.pipelines.pipeline definition](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/resources-pipelines-pipeline?view=azure-pipelines)
* Content Source: [content/resources-pipelines-pipeline.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/resources-pipelines-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@petrkoutnycz I will get this updated. `<Alias>` refers to the name of the pipeline resource. I will clarify that in the docs and add an example.
