### ISSUE TITLE
More information about latest available version

### ISSUE THREAD

**Issue by JanTrichter** [MicrosoftDocs/azure-devops-yaml-schema#51]
Hey!
I was just working with this plugin and using dotnet sdk 6.0.x which downloads .NET 6.0.9 instead of the latest patch version which is 6.0.10.

How can I see if the latest patch version is available and when will 6.0.10 be available?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a9c6264c-6eed-8e94-0d93-47983e69060c
* Version Independent ID: a9c6264c-6eed-8e94-0d93-47983e69060c
* Content: [UseDotNet@2 - Use dotnet v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/use-dotnet-v2?view=azure-pipelines)
* Content Source: [task-reference/use-dotnet-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/use-dotnet-v2.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@JanTrichter -- Jan, thank you again for your feedback and question.  This may help answer:
- [Azure DevOps Roadmap](https://learn.microsoft.com/en-us/azure/devops/release-notes/features-timeline)

cc @steved0x for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by JanTrichter** [comment]
@WilliamAntonRohm Thanks for the answer but I couldn't find which .NET Version is the latest patch used for .NET 6 from your link.

**Comment by WilliamAntonRohm** [comment]
@JanTrichter -- Jan, thank you for your follow-up.  This link may help:
- [.NET October 2022 Updates – .NET 6.0.10 and .NET Core 3.1.30](https://devblogs.microsoft.com/dotnet/october-2022-updates)

**Comment by JanTrichter** [comment]
@WilliamAntonRohm I found [this url](https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json) at the end of the [versionfetcher.ts](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/UseDotNetV2/versionfetcher.ts) file of the task which hosts a json file which contains the latest versions of .NET that is ised by the task to determine which version to download. When I run `dotnet --info` in the AppService console it still shows .NET 6.0.9 as the host version. So looks like there is something wrong with the task. Thanks for your help!

**Comment by WilliamAntonRohm** [comment]
@JanTrichter -- Jan, thank you for your research.  You're welcome to add this issue here:
- [Azure DevOps Feedback](https://developercommunity.visualstudio.com/AzureDevOps)
