### ISSUE TITLE
steps.download 'specific' can't reference variable or parameter for the pipeline resource identifier

### ISSUE THREAD

**Issue by Rich79923** [MicrosoftDocs/azure-devops-yaml-schema#52]
When trying to set pipeline resource identifier using a parameter or $(Resources.TriggeringAlias) the pipeline just hangs. Only seems to work if we hard code the Resource Pipeline name. 

This restriction means we can't have a template for deploying app service which can be used by multiple triggering pipelines.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0727646b-b2de-43e7-66bb-4d1a4e149801
* Version Independent ID: 0727646b-b2de-43e7-66bb-4d1a4e149801
* Content: [steps.download definition](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-download?view=azure-pipelines)
* Content Source: [content/steps-download.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/steps-download.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@Rich79923 -- Rich, thank you for your feedback.  This repo is solely for documentation issues, and this seems to be product-related.  Please add it here:
- [Visual Studio Feedback](https://developercommunity.visualstudio.com/AzureDevOps)  

cc @steved0x for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
