### ISSUE TITLE
AzureFunctionApp@1: Clarify the azureSubscription property

### ISSUE THREAD

**Issue by 01F0** [MicrosoftDocs/azure-devops-yaml-schema#53]
Hi!

The `AzureFunctionApp@1`  has an `azureSubscription` property and the comment in the docs says "Required. Azure subscription.". 

To me, it looked like I was supposed to add the Azure subscription GUID here and I even tried the name.

What was needed though, was a service connection, which neither the name or comment indicates. 🤔

Can you add something to the comment that indicates this? 🙏🏻

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 84a23158-e322-4577-5dcc-de0c380dc186
* Version Independent ID: 84a23158-e322-4577-5dcc-de0c380dc186
* Content: [AzureFunctionApp@1 - Azure Functions v1 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-function-app-v1?view=azure-pipelines)
* Content Source: [task-reference/azure-function-app-v1.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/azure-function-app-v1.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by juliakm** [comment]
Thanks for your feedback! I'll update the doc now.
