### ISSUE TITLE
When will Azure pipeline support Powershell version 7? 

### ISSUE THREAD

**Issue by kevinjwa611** [MicrosoftDocs/azure-devops-yaml-schema#54]
I am trying to run ForEachObject-Parallel, but that is a feature new to POwershell 7 and the pipeline is unable to run it as of now. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5de2083f-ba71-fce1-ec99-91ee90d0d001
* Version Independent ID: 5de2083f-ba71-fce1-ec99-91ee90d0d001
* Content: [AzurePowerShell@5 - Azure PowerShell v5 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-powershell-v5?view=azure-pipelines)
* Content Source: [task-reference/azure-powershell-v5.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/azure-powershell-v5.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@kevinjwa611 -- Kevin, thank you for your question.  Please consider this resource:
- [Azure DevOps Roadmap](https://learn.microsoft.com/azure/devops/release-notes/features-timeline)

cc @steved0x for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
