### ISSUE TITLE
Add more detailed example for extraProperties

### ISSUE THREAD

**Issue by ASaiAnudeep** [MicrosoftDocs/azure-devops-yaml-schema#55]
Add more detailed example on the usage of **extraProperties** syntax

```yaml
extraProperties: |
  sonar.projectKey=project-key
  sonar.projectName=project-name
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1e3a14f7-7b13-bbac-e401-d9a4379e6e8c
* Version Independent ID: 1e3a14f7-7b13-bbac-e401-d9a4379e6e8c
* Content: [SonarQubePrepare@5 - Prepare Analysis Configuration v5 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/sonar-qube-prepare-v5?view=azure-pipelines)
* Content Source: [task-reference/sonar-qube-prepare-v5.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/sonar-qube-prepare-v5.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
