### ISSUE TITLE
Update the required agent version of BashV3 task!

### ISSUE THREAD

**Issue by douggutaby** [MicrosoftDocs/azure-devops-yaml-schema#56]
[Enter feedback here]
Please update the required agent version! Our pipelines are failed because of the changed bash task and our 2.204 agent version.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 18090cba-5cc1-9d3d-8de0-44e0eee0215f
* Version Independent ID: 18090cba-5cc1-9d3d-8de0-44e0eee0215f
* Content: [Bash@3 - Bash v3 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/bash-v3?view=azure-pipelines#requirements)
* Content Source: [task-reference/bash-v3.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/bash-v3.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@douggutaby -- thank you for your feedback.  That page was updated today, and the [Requirements](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/bash-v3?view=azure-pipelines#requirements) section now lists:

> Agent version | 2.206.1 or greater
