### ISSUE TITLE
createExtractDirectory description is wrong

### ISSUE THREAD

**Issue by nheath99** [MicrosoftDocs/azure-devops-yaml-schema#62]
Existing:

By default, the task creates a directory similar to JAVA_HOME_8_X64_OpenJDK_zip for extracting JDK. This option disables the creation of that folder and, if set to **true**, JDK is located in the root of jdkDestinationDirectory instead.

Should be:

By default, the task creates a directory similar to JAVA_HOME_8_X64_OpenJDK_zip for extracting JDK. This option disables the creation of that folder and, if set to **false**, JDK is located in the root of jdkDestinationDirectory instead.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 32a61652-2b7b-59da-3a2b-f25a4ca87123
* Version Independent ID: 32a61652-2b7b-59da-3a2b-f25a4ca87123
* Content: [JavaToolInstaller@0 - Java tool installer v0 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/java-tool-installer-v0?view=azure-pipelines&viewFallbackFrom=azure-devops)
* Content Source: [task-reference/java-tool-installer-v0.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/java-tool-installer-v0.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@steved0x -- Steve, please review [private PR 271](https://github.com/MicrosoftDocs/azure-devops-yaml-schema-pr/pull/271).
