### ISSUE TITLE
How to reference pipeline variables in the script?

### ISSUE THREAD

**Issue by selism** [MicrosoftDocs/azure-devops-yaml-schema#63]
Please add an example on how to use the value of a pipeline variable in the script.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 56abb0df-205e-fa32-a5c7-ba83df4c120e
* Version Independent ID: 56abb0df-205e-fa32-a5c7-ba83df4c120e
* Content: [CmdLine@2 - Command line v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/cmd-line-v2?view=azure-pipelines&viewFallbackFrom=azure-devops)
* Content Source: [task-reference/cmd-line-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/cmd-line-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
