### ISSUE TITLE
Is there a reason why download does not support custom path?

### ISSUE THREAD

**Issue by quasarea** [MicrosoftDocs/azure-devops-yaml-schema#65]
In https://learn.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml there is a note that:
> The download keyword is a shortcut for the [Download Pipeline Artifact](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/download-pipeline-artifact-v2) task.

The download-pipeline-artifact task supports `path` parameter while the download task dumps artifacts into a predefined location, is there a reason for such inconsistency?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0727646b-b2de-43e7-66bb-4d1a4e149801
* Version Independent ID: 0727646b-b2de-43e7-66bb-4d1a4e149801
* Content: [steps.download definition](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-download?view=azure-pipelines)
* Content Source: [content/steps-download.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/steps-download.md)
* Service: **azure-devops-pipelines**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
