### ISSUE TITLE
Documentation is missing some details

### ISSUE THREAD

**Issue by rangus-devopssvcs** [MicrosoftDocs/azure-devops-yaml-schema#66]
deploymentName: This does not mention that there is a limit to the length of the name. It fails when it is > 64 characters. Would be super useful if that was documented, as well as some explainers on how to manage this (i.e. how to truncate a value > 64, or even change this so that it automatically truncates (or gives you the option to do so)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 39f9c731-0172-2061-b972-3870d69ac358
* Version Independent ID: 39f9c731-0172-2061-b972-3870d69ac358
* Content: [AzureResourceManagerTemplateDeployment@3 - ARM template deployment v3 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-resource-manager-template-deployment-v3?view=azure-pipelines)
* Content Source: [task-reference/azure-resource-manager-template-deployment-v3.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/azure-resource-manager-template-deployment-v3.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
