### ISSUE TITLE
version set to ...-snapshot for maven package type yields not the latest but all snapshots

### ISSUE THREAD

**Issue by dermoritz** [MicrosoftDocs/azure-devops-yaml-schema#68]
I need to download the latest snapshot for a given artifact and version:

```
- task: DownloadPackage@1
  inputs: 
    packageType: 'maven'
    feed: 'Artifacts'
    definition: 'package:cc-messagerelay'
    version: '0.0.1-snapshot'
    files: '*.jar'
    downloadPath: './target/'
```

but this does not yield the latest snapshot of version 0.0.1 but all snapshots e.g.:

```
##[debug]rm -rf /home/vsts/work/1/s/target/cc-messagerelay-0.0.1-20221212.120339-19.jar
##[debug]rm -rf /home/vsts/work/1/s/target/cc-messagerelay-0.0.1-20221212.105844-18.jar
...
##[debug]rm -rf /home/vsts/work/1/s/target/cc-messagerelay-0.0.1-20221208.131120-3.jar
##[debug]rm -rf /home/vsts/work/1/s/target/cc-messagerelay-0.0.1-20221208.130455-2.jar
##[debug]rm -rf /home/vsts/work/1/s/target/cc-messagerelay-0.0.1-20221207.165101-1.jar
```

So how to acquire the the latest snapshot of a given version?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 769d848b-315d-86bf-1673-5a87f87a970d
* Version Independent ID: 769d848b-315d-86bf-1673-5a87f87a970d
* Content: [DownloadPackage@1 - Download package v1 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/download-package-v1?view=azure-pipelines)
* Content Source: [task-reference/download-package-v1.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/download-package-v1.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
See also #67.

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
