### ISSUE TITLE
Add link to file matching patterns page for SearchPattern attribute

### ISSUE THREAD

**Issue by jamesdooleymsft** [MicrosoftDocs/azure-devops-yaml-schema#72]
SearchPattern doesn't describe the format of the search pattern, so users have to use Google or StackOverflow to find out its format. 
 It'd be helpful to add a direct link to https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns to make it faster to discover that information and ensure customers don't use out-of-date information from a web search.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4d97490d-94e9-7c19-f87a-0594ff604c3e
* Version Independent ID: 4d97490d-94e9-7c19-f87a-0594ff604c3e
* Content: [PublishSymbols@2 - Index sources and publish symbols v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-symbols-v2?view=azure-pipelines)
* Content Source: [task-reference/publish-symbols-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/publish-symbols-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Fixed by https://github.com/MicrosoftDocs/azure-devops-yaml-schema/pull/73
