### ISSUE TITLE
Please add links to arguments for the 'test' command.

### ISSUE THREAD

**Issue by DevGallie** [MicrosoftDocs/azure-devops-yaml-schema#75]
Please add links to arguments for the 'test' command. It would make the page more usable.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5825539f-634b-03d6-35f0-b532177a5e3b
* Version Independent ID: 5825539f-634b-03d6-35f0-b532177a5e3b
* Content: [DotNetCoreCLI@2 - .NET Core v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/dotnet-core-cli-v2?view=azure-pipelines)
* Content Source: [task-reference/dotnet-core-cli-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/dotnet-core-cli-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
