### ISSUE TITLE
VSTest@2 input vsTestVersion description outdated?

### ISSUE THREAD

**Issue by florelis** [MicrosoftDocs/azure-devops-yaml-schema#78]
Description for `vsTestVersion` input on VSTest@2 states:

> Specifies the version of Visual Studio Test to use. If latest is specified, this input chooses Visual Studio 2017 or Visual Studio 2015 depending on what is installed.

This may need to be updated to include VS 2019

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5a378422-4758-62c7-1793-7ce4724079aa
* Version Independent ID: 5a378422-4758-62c7-1793-7ce4724079aa
* Content: [VSTest@2 - Visual Studio Test v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/vstest-v2?view=azure-pipelines)
* Content Source: [task-reference/vstest-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/vstest-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
I'll get this updated today, thank you for letting us know.
