### ISSUE TITLE
Support for HCL2 files

### ISSUE THREAD

**Issue by fbotero-exxonmobil** [MicrosoftDocs/azure-devops-yaml-schema#81]
PackerBuild@1 task throws an error when using HCL2 templates as it tries to run "packer fix" command, that is only supported for json files

**Comment by steved0x** [comment]
Thank you for your feedback. We are migrating this issue to our new documentation feedback system, and closing this issue.
 
As we phase out GitHub issues for this repository, we encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page. For more information on our feedback systems, see https://aka.ms/contentuserfeedback.
