### ISSUE TITLE
XCODETASK@5 INCOMPATIBLE WITH XCODE VERSION > 13

### ISSUE THREAD

**Issue by amey4753** [MicrosoftDocs/azure-devops-yaml-schema#82]
As per xcode task 5 documentation it only supports xcode version 8-11 .
Do you have any updates for xcode versions above 13 which we are using in our org.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 32f37803-2465-bc77-b00b-1530ce74ee35
* Version Independent ID: 32f37803-2465-bc77-b00b-1530ce74ee35
* Content: [Xcode@5 - Xcode v5 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/xcode-v5?view=azure-pipelines)
* Content Source: [task-reference/xcode-v5.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/xcode-v5.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by JRendleman** [comment]
Is there a timeline on this? Our org is also facing a similar issue.

**Comment by amey4753** [comment]
No timeline I guess we couldn’t wait  eventually came around with
workaround for now

**Comment by JRendleman** [comment]
What workaround did you all come up with?

**Comment by steved0x** [comment]
@amey4753 Sorry for the delay on responding to this. According to the inputs of the XCode@5 task (Azure DevOps Server 2022 and Azure DevOps Services) it supports the following versions:

xcodeVersion - Xcode version
string. Allowed values: 8 (Xcode 8), 9 (Xcode 9), 10 (Xcode 10), 11 (Xcode 11), 12 (Xcode 12), 13 (Xcode 13), default, specifyPath (Specify path). Default value: default.

The task assistant for XCode@5 uses this same list for choosing the version
![image](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/assets/1580889/4df8c584-f6ff-4aa8-885a-473c2c1345d9)


Down in the Remarks section it erroneously states:

This version of the task is compatible with Xcode 8 - 11. Features that were solely to maintain compatibility with Xcode 7 have been removed. This task has better options for using Microsoft-hosted macOS agents.

I will get that fixed today.

Thank you for letting us know.
