### ISSUE TITLE
symlink out of order

### ISSUE THREAD

**Issue by leasley199** [MicrosoftDocs/azure-devops-yaml-schema#93]
Given the context of the command/example they are trying to create a symlink for the securefilepath. The symlink command is out of order where they specify the source file is /etc/ssl/certs/ and symlink is $(caCertificate.secureFilePath) when it should be vise-versa.

Source: https://linuxize.com/post/how-to-create-symbolic-links-in-linux-using-the-ln-command

<code>ln -s my_source_file.txt my_symlink.txt</code>

```yaml
- script: |
.....
    sudo ln -s -t /etc/ssl/certs/ $(caCertificate.secureFilePath)
```
Should be 
```yaml
    sudo ln -s -t $(caCertificate.secureFilePath) /etc/ssl/certs/ 
```

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a24ead07-ef29-593f-36dc-4b5bb0beea24
* Version Independent ID: a24ead07-ef29-593f-36dc-4b5bb0beea24
* Content: [DownloadSecureFile@1 - Download secure file v1 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/download-secure-file-v1?view=azure-pipelines#examples)
* Content Source: [task-reference/download-secure-file-v1.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/download-secure-file-v1.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by leasley199** [comment]
update... the -t is not needed.. should just be  sudo ln -s $(caCertificate.secureFilePath) /etc/ssl/certs/ .. -t throw me for a loop.

**Comment by WilliamAntonRohm** [comment]
@steved0x -- Steve, please review this update in [private PR 302](https://github.com/MicrosoftDocs/azure-devops-yaml-schema-pr/pull/302).
