### ISSUE TITLE
AzureResourceManagerTemplateDeployment@3 task supports Bicep

### ISSUE THREAD

**Issue by A-AontwSR** [MicrosoftDocs/azure-devops-yaml-schema#97]
Besides deploying ARM templates, this task now also supports deploying **Bicep**. See [readme AzureResourceManagerTemplateDeploymentV3](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureResourceManagerTemplateDeploymentV3).
The ability to deploy Bicep is not yet described in this reference.

Please describe at parameter `csmFile` that besides an ARM template also a Bicep file can be used. And make a mention in the `Remarks` about the possibility of using a Bicep file as input (provided Az CLI version >= 2.20.0 is installed).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 39f9c731-0172-2061-b972-3870d69ac358
* Version Independent ID: 39f9c731-0172-2061-b972-3870d69ac358
* Content: [AzureResourceManagerTemplateDeployment@3 - ARM template deployment v3 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-resource-manager-template-deployment-v3?view=azure-pipelines)
* Content Source: [task-reference/azure-resource-manager-template-deployment-v3.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/azure-resource-manager-template-deployment-v3.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by A-AontwSR** [comment]
@steved0x  Is it known when the change will be made? And when it will be visible on the page in learn.micosoft.com?

**Comment by steved0x** [comment]
@A-AontwSR I am publishing an updatetoday  which includes Bicep support for the task, in the inputs for templateLocation, csmFile, csmParametersFile, and a general note in the task remarks. This will be live later today. Thank you for letting us know.
